/* The Programs folder: copies of the engine's five samples, then seven music programs.
   Written for a machine with files: a program's output is written with WRITE (7,f), and each
   string is one line of the text. The output is the same as the originals'. Data only. */
var PROGRAMS = {
  engine: 5,
  list: [
    { name: "Squares and roots", lines: [
      "C     SQUARES AND SQUARE ROOTS",
      "      WRITE (6,10)",
      "   10 FORMAT (1H1,5X,1HN,6X,6HSQUARE,5X,4HROOT)",
      "      DO 20 I = 1, 5",
      "      X = FLOAT(I)",
      "      Y = SQRT(X)",
      "      ISQ = I*I",
      "      WRITE (6,30) I, ISQ, Y",
      "   20 CONTINUE",
      "   30 FORMAT (1X,I6,I12,F9.4)",
      "      STOP",
      "      END"
    ] },
    { name: "Heron's formula", lines: [
      "C     AREA OF A TRIANGLE BY HERONS FORMULA",
      "      READ (5,10) IA, IB, IC",
      "   10 FORMAT (3I5)",
      "      S = FLOAT(IA+IB+IC)/2.0",
      "      AREA = SQRT(S*(S-FLOAT(IA))*(S-FLOAT(IB))*(S-FLOAT(IC)))",
      "      WRITE (6,20) IA, IB, IC, AREA",
      "   20 FORMAT (1H0,3HA =,I5,5H  B =,I5,5H  C =,I5,8H  AREA =,F10.2)",
      "      STOP",
      "      END",
      "    3    4    5"
    ] },
    { name: "Largest of N values", lines: [
      "C     LARGEST VALUE IN A SET OF NUMBERS",
      "      DIMENSION A(100)",
      "      READ (5,100) N",
      "  100 FORMAT (I5)",
      "      DO 5 I = 1, N",
      "      READ (5,101) A(I)",
      "    5 CONTINUE",
      "  101 FORMAT (F10.2)",
      "      BIGA = A(1)",
      "      DO 20 I = 2, N",
      "      IF (BIGA - A(I)) 10, 20, 20",
      "   10 BIGA = A(I)",
      "   20 CONTINUE",
      "      WRITE (6,102) N, BIGA",
      "  102 FORMAT (1H ,10HLARGEST OF,I4,8H VALUES:,F10.2)",
      "      STOP",
      "      END",
      "    5",
      "3.5",
      "-2.0",
      "17.25",
      "9.0",
      "17.0"
    ] },
    { name: "Multiples of 3 below 20", lines: [
      "C     WRITE THE MULTIPLES OF 3 BELOW 20 TO THE OUTPUT, ONE PER LINE",
      "      DO 10 N = 0, 19",
      "      IF (MOD(N,3)) 10, 5, 10",
      "    5 WRITE (7,20) N",
      "   10 CONTINUE",
      "   20 FORMAT (I5)",
      "      STOP",
      "      END"
    ] },
    { name: "Sieve generator (after Xenakis)", lines: [
      "C     SIEVE GENERATOR, AFTER XENAKIS",
      "C     A RESIDUAL CLASS M(S) IS EVERY INTEGER X WITH X-S DIVISIBLE BY M.",
      "C     DATA LINE 1 (3I5): MODE, N, LIMIT",
      "C        MODE 1 = UNION OF THE N CLASSES",
      "C        MODE 2 = INTERSECTION OF THE N CLASSES",
      "C        MODE 3 = COMPLEMENT OF THE UNION",
      "C        N IS 1 TO 10. THE SIEVE IS TESTED ON 0 TO LIMIT-1.",
      "C     DATA LINES 2 TO N+1 (2I5): M, S",
      "C     EACH MEMBER IS PRINTED WITH ITS INTERVAL FROM THE LAST ONE,",
      "C     AND WRITTEN TO THE OUTPUT, ONE PER LINE, FOR USE AS DATA.",
      "      DIMENSION IM(10), IS(10)",
      "      READ (5,10) MODE, N, LIMIT",
      "   10 FORMAT (3I5)",
      "      DO 20 K = 1, N",
      "      READ (5,11) IM(K), IS(K)",
      "   20 CONTINUE",
      "   11 FORMAT (2I5)",
      "      WRITE (6,30) MODE, N, LIMIT",
      "   30 FORMAT (1H1,'SIEVE  MODE =',I2,'  N =',I3,'  LIMIT =',I6)",
      "      WRITE (6,31)",
      "   31 FORMAT (1H0,5X,'K',3X,'MEMBER',3X,'INTERVAL')",
      "      NM = 0",
      "      LAST = 0",
      "      DO 60 J = 1, LIMIT",
      "      NV = J - 1",
      "      NH = 0",
      "      DO 40 K = 1, N",
      "      IF (MOD(MOD(NV-IS(K),IM(K))+IM(K),IM(K))) 40, 35, 40",
      "   35 NH = NH + 1",
      "   40 CONTINUE",
      "      MEMB = 0",
      "      IF (MODE .EQ. 1 .AND. NH .GT. 0) MEMB = 1",
      "      IF (MODE .EQ. 2 .AND. NH .EQ. N) MEMB = 1",
      "      IF (MODE .EQ. 3 .AND. NH .EQ. 0) MEMB = 1",
      "      IF (MEMB .EQ. 0) GO TO 60",
      "      NM = NM + 1",
      "      ITV = NV - LAST",
      "      LAST = NV",
      "      WRITE (7,34) NV",
      "      IF (NM .EQ. 1) GO TO 50",
      "      WRITE (6,32) NM, NV, ITV",
      "      GO TO 60",
      "   50 WRITE (6,33) NM, NV",
      "   60 CONTINUE",
      "      WRITE (6,36) NM",
      "      STOP",
      "   32 FORMAT (1X,I6,I9,I11)",
      "   33 FORMAT (1X,I6,I9)",
      "   34 FORMAT (I5)",
      "   36 FORMAT (1H0,I5,' MEMBERS')",
      "      END",
      "    1    2   20",
      "    5    2",
      "    5    3"
    ] },
    { name: "Sieve scale (a melody)", lines: [
      "C     SIEVE SCALE, AFTER XENAKIS",
      "C     A SIEVE TAKEN OVER THE SEMITONES ABOVE A BASE NOTE GIVES A SCALE,",
      "C     WHICH NEED NOT REPEAT AT THE OCTAVE. A WALK BY CHANCE ON THE SCALE",
      "C     UP TO TWO STEPS UP OR DOWN AT A TIME, MAKES A MELODY.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE 1 (3I5): N CLASSES (1 TO 10), RANGE IN SEMITONES (UP TO",
      "C        100), BASE NOTE. LINES 2 TO N+1 (2I5): M, S. THE SCALE IS THEIR",
      "C        UNION. LAST LINE (2I5): SEED, NUMBER OF NOTES.",
      "      DIMENSION IM(10), IS(10), ISC(100)",
      "      READ (5,10) N, IRANGE, IBASE",
      "   10 FORMAT (3I5)",
      "      DO 20 K = 1, N",
      "      READ (5,11) IM(K), IS(K)",
      "   20 CONTINUE",
      "   11 FORMAT (2I5)",
      "      READ (5,11) IX, NN",
      "C     THE SCALE: EVERY SEMITONE IN AT LEAST ONE CLASS",
      "      NS = 0",
      "      DO 40 J = 1, IRANGE",
      "      NV = J - 1",
      "      NH = 0",
      "      DO 30 K = 1, N",
      "      IF (MOD(MOD(NV-IS(K),IM(K))+IM(K),IM(K)) .EQ. 0) NH = NH + 1",
      "   30 CONTINUE",
      "      IF (NH .EQ. 0) GO TO 40",
      "      NS = NS + 1",
      "      ISC(NS) = IBASE + NV",
      "   40 CONTINUE",
      "      WRITE (6,45) NS",
      "   45 FORMAT (1H1,'SIEVE SCALE OF',I4,' NOTES'/1H0,'  STEP  NOTE')",
      "      DO 47 K = 1, NS",
      "      WRITE (6,46) K, ISC(K)",
      "   47 CONTINUE",
      "   46 FORMAT (1X,I6,I6)",
      "      IF (NS .LT. 3) GO TO 90",
      "      WRITE (6,50)",
      "   50 FORMAT (1H0,'MELODY'/1H0,'     K  TIME  NOTE   LEN')",
      "C     THE WALK",
      "      IP = (NS + 1)/2",
      "      IT = 0",
      "      DO 70 K = 1, NN",
      "      IX = MOD(171*IX, 30269)",
      "      IP = IP + MOD(IX, 5) - 2",
      "      IF (IP .LT. 1) IP = 2 - IP",
      "      IF (IP .GT. NS) IP = 2*NS - IP",
      "      IX = MOD(171*IX, 30269)",
      "      LEN = 1 + MOD(IX, 2)",
      "      IF (MOD(K, 8) .EQ. 0) LEN = 4",
      "      LOUD = 5 + MOD(IX/2, 4)",
      "      NOTE = ISC(IP)",
      "      WRITE (6,60) K, IT, NOTE, LEN",
      "      WRITE (7,65) IT, NOTE, LEN, LOUD",
      "      IT = IT + LEN",
      "   70 CONTINUE",
      "      STOP",
      "   90 WRITE (6,91)",
      "   91 FORMAT (1H0,'THE SCALE NEEDS AT LEAST 3 NOTES.')",
      "      STOP",
      "   60 FORMAT (1X,4I6)",
      "   65 FORMAT (4I5)",
      "      END",
      "    3   36   48",
      "    5    0",
      "    7    2",
      "    8    3",
      " 1965   40"
    ] },
    { name: "Two rhythm sieves", lines: [
      "C     TWO RHYTHM SIEVES",
      "C     TWO SIEVES ARE TAKEN OVER A CYCLE OF PULSES. THE FIRST STRIKES A",
      "C     LOW DRUM AND THE SECOND A HIGH ONE, AND WHERE BOTH FALL TOGETHER",
      "C     THE STROKE IS LOUDER. XENAKIS BUILT THE RHYTHMS OF PSAPPHA (1975),",
      "C     FOR SOLO PERCUSSION, FROM SIEVES OF THIS KIND.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE 1 (2I5): CYCLE LENGTH IN PULSES, NUMBER OF CYCLES",
      "C     LINE 2 (2I5): NOTE OF THE LOW DRUM, N CLASSES, THEN N LINES (2I5)",
      "C        OF M, S. THEN THE SAME FOR THE HIGH DRUM. EACH SIEVE IS A UNION",
      "      DIMENSION IM(10,2), IS(10,2), NC(2), NOTE(2), IH(2)",
      "      READ (5,10) LC, NR",
      "   10 FORMAT (2I5)",
      "      DO 25 L = 1, 2",
      "      READ (5,10) NOTE(L), NC(L)",
      "      NK = NC(L)",
      "      DO 20 K = 1, NK",
      "      READ (5,10) IM(K,L), IS(K,L)",
      "   20 CONTINUE",
      "   25 CONTINUE",
      "      WRITE (6,30) LC, NR",
      "   30 FORMAT (1H1,'TWO RHYTHM SIEVES, A CYCLE OF',I4,' PULSES PLAYED',",
      "     1       I3,' TIMES'/1H0,' PULSE  STROKE')",
      "      NP = 0",
      "      DO 60 IR = 1, NR",
      "      DO 55 J = 1, LC",
      "      NV = J - 1",
      "      DO 45 L = 1, 2",
      "      IH(L) = 0",
      "      NK = NC(L)",
      "      DO 40 K = 1, NK",
      "      IF (MOD(MOD(NV-IS(K,L),IM(K,L))+IM(K,L),IM(K,L)) .EQ. 0) IH(L) = 1",
      "   40 CONTINUE",
      "   45 CONTINUE",
      "      IT = (IR - 1)*LC + NV",
      "      LOUD = 6",
      "      IF (IH(1) + IH(2) .EQ. 2) LOUD = 9",
      "      IF (IH(1) .EQ. 1) WRITE (7,50) IT, NOTE(1), 1, LOUD",
      "      IF (IH(2) .EQ. 1) WRITE (7,50) IT, NOTE(2), 1, LOUD",
      "      NP = NP + IH(1) + IH(2)",
      "C     PRINT THE FIRST CYCLE AS A SCORE",
      "      IF (IR .GT. 1) GO TO 55",
      "      KIND = 1 + IH(1) + 2*IH(2)",
      "      GO TO (51,52,53,54), KIND",
      "   51 WRITE (6,71) NV",
      "      GO TO 55",
      "   52 WRITE (6,72) NV",
      "      GO TO 55",
      "   53 WRITE (6,73) NV",
      "      GO TO 55",
      "   54 WRITE (6,74) NV",
      "   55 CONTINUE",
      "   60 CONTINUE",
      "      WRITE (6,75) NP",
      "      STOP",
      "   50 FORMAT (4I5)",
      "   71 FORMAT (1X,I6,'  .')",
      "   72 FORMAT (1X,I6,'  LOW')",
      "   73 FORMAT (1X,I6,'          HIGH')",
      "   74 FORMAT (1X,I6,'  LOW     HIGH')",
      "   75 FORMAT (1H0,I5,' STROKES WRITTEN')",
      "      END",
      "   40    2",
      "   41    3",
      "    8    0",
      "    8    3",
      "    8    6",
      "   72    2",
      "    5    1",
      "    7    2"
    ] },
    { name: "Stochastic cloud (after Achorripsis)", lines: [
      "C     STOCHASTIC CLOUD, AFTER ACHORRIPSIS (1956-57)",
      "C     IN ACHORRIPSIS XENAKIS USED THE POISSON LAW TO DECIDE HOW MANY",
      "C     EVENTS FALL IN EACH CELL OF TIME. HERE EVENTS ARRIVE AT RANDOM,",
      "C     AT A MEAN RATE OF LAMBDA PER PULSE, SO THE GAPS BETWEEN THEM",
      "C     FOLLOW THE EXPONENTIAL LAW, AND THEIR NOTES FALL IN A BAND THAT",
      "C     RISES THREE OCTAVES OVER THE CLOUD. THE PRINTOUT COUNTS EVENTS IN",
      "C     CELLS OF 4 PULSES AND SETS THE COUNTS AGAINST THE POISSON LAW.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE (I5,F5.2,3I5): SEED, LAMBDA, PULSES (UP TO 400), LOWEST",
      "C        NOTE AT THE START, WIDTH OF THE BAND IN SEMITONES",
      "      DIMENSION NCELL(100), NOBS(13)",
      "      READ (5,10) IX, RATE, NP, LOW, NW",
      "   10 FORMAT (I5,F5.2,3I5)",
      "      DO 15 K = 1, 100",
      "      NCELL(K) = 0",
      "   15 CONTINUE",
      "      T = 0.0",
      "      NE = 0",
      "   30 IX = MOD(171*IX, 30269)",
      "      U = (FLOAT(IX) + 1.0)/30270.0",
      "      T = T - ALOG(U)/RATE",
      "      IT = INT(T)",
      "      IF (IT .GE. NP) GO TO 50",
      "      IX = MOD(171*IX, 30269)",
      "      NOTE = LOW + (36*IT)/NP + MOD(IX, NW)",
      "      IX = MOD(171*IX, 30269)",
      "      LEN = 1 + MOD(IX, 3)",
      "      LOUD = 3 + MOD(IX/3, 6)",
      "      WRITE (7,40) IT, NOTE, LEN, LOUD",
      "   40 FORMAT (4I5)",
      "      NE = NE + 1",
      "      KC = IT/4 + 1",
      "      NCELL(KC) = NCELL(KC) + 1",
      "      GO TO 30",
      "C     HOW MANY CELLS HOLD 0, 1, 2, ... EVENTS",
      "   50 NCL = NP/4",
      "      DO 55 K = 1, 13",
      "      NOBS(K) = 0",
      "   55 CONTINUE",
      "      DO 60 K = 1, NCL",
      "      KK = NCELL(K) + 1",
      "      IF (KK .GT. 13) KK = 13",
      "      NOBS(KK) = NOBS(KK) + 1",
      "   60 CONTINUE",
      "      WRITE (6,65) NE, NP, NCL",
      "   65 FORMAT (1H1,'STOCHASTIC CLOUD:',I5,' EVENTS IN',I5,' PULSES'/",
      "     1       1H0,I5,' CELLS OF 4 PULSES'/1H0,'EVENTS    CELLS  POISSON')",
      "      XM = 4.0*RATE",
      "      P = EXP(-XM)",
      "      DO 75 K = 1, 13",
      "      KE = K - 1",
      "      E = P*FLOAT(NCL)",
      "      WRITE (6,70) KE, NOBS(K), E",
      "      P = P*XM/FLOAT(K)",
      "   75 CONTINUE",
      "   70 FORMAT (1X,I5,I9,F9.1)",
      "      STOP",
      "      END",
      " 1957 0.60  192   36   12"
    ] },
    { name: "Markov melody (after Analogique)", lines: [
      "C     MARKOV MELODY, AFTER ANALOGIQUE A AND B (1958-59)",
      "C     IN ANALOGIQUE A AND B XENAKIS LET MARKOV CHAINS CHOOSE EACH NEW",
      "C     STATE OF THE MUSIC FROM THE ONE BEFORE IT. HERE A CHAIN MOVES",
      "C     AMONG FIVE NOTES. ROW I OF THE TABLE GIVES THE CHANCES, IN",
      "C     PERCENT, OF GOING FROM NOTE I TO EACH NOTE. EDIT THE TABLE TO",
      "C     CHANGE THE CHARACTER OF THE TUNE.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE 1 (3I5): SEED, NUMBER OF NOTES, FIRST NOTE (1 TO 5)",
      "C     LINE 2 (5I5): THE FIVE NOTES. LINES 3 TO 7 (5I5): THE TABLE.",
      "      DIMENSION NT(5), IP(5,5), NUSE(5)",
      "      READ (5,10) IX, NN, IS",
      "   10 FORMAT (3I5)",
      "      READ (5,11) NT(1), NT(2), NT(3), NT(4), NT(5)",
      "   11 FORMAT (5I5)",
      "      DO 20 I = 1, 5",
      "      READ (5,11) IP(I,1), IP(I,2), IP(I,3), IP(I,4), IP(I,5)",
      "      NUSE(I) = 0",
      "      ISUM = IP(I,1) + IP(I,2) + IP(I,3) + IP(I,4) + IP(I,5)",
      "      IF (ISUM .NE. 100) WRITE (6,15) I, ISUM",
      "   20 CONTINUE",
      "   15 FORMAT (1X,'ROW',I2,' OF THE TABLE ADDS UP TO',I4,', NOT 100')",
      "      WRITE (6,25)",
      "   25 FORMAT (1H1,'MARKOV MELODY'/1H0,'     K STATE  NOTE  TIME')",
      "      IT = 0",
      "      DO 60 K = 1, NN",
      "      NOTE = NT(IS)",
      "      NUSE(IS) = NUSE(IS) + 1",
      "      LEN = 1",
      "      IF (IS .EQ. 1) LEN = 2",
      "      IF (MOD(K, 12) .EQ. 0) LEN = 4",
      "      WRITE (6,30) K, IS, NOTE, IT",
      "   30 FORMAT (1X,4I6)",
      "      WRITE (7,35) IT, NOTE, LEN, 6",
      "   35 FORMAT (4I5)",
      "      IT = IT + LEN",
      "C     CHOOSE THE NEXT NOTE FROM ROW IS OF THE TABLE",
      "      IX = MOD(171*IX, 30269)",
      "      IR = MOD(IX, 100)",
      "      NEXT = 0",
      "      IACC = 0",
      "      DO 40 J = 1, 5",
      "      IACC = IACC + IP(IS,J)",
      "      IF (NEXT .EQ. 0 .AND. IR .LT. IACC) NEXT = J",
      "   40 CONTINUE",
      "      IF (NEXT .EQ. 0) NEXT = IS",
      "      IS = NEXT",
      "   60 CONTINUE",
      "      WRITE (6,65)",
      "   65 FORMAT (1H0,'TIMES EACH NOTE WAS PLAYED'/1H0,' STATE  NOTE TIMES')",
      "      DO 75 I = 1, 5",
      "      WRITE (6,70) I, NT(I), NUSE(I)",
      "   75 CONTINUE",
      "   70 FORMAT (1X,3I6)",
      "      STOP",
      "      END",
      " 1958   48    1",
      "   62   64   67   69   72",
      "   10   40   30   10   10",
      "   30   10   40   10   10",
      "   20   20   10   40   10",
      "   10   10   40   10   30",
      "   40   10   20   20   10"
    ] },
    { name: "String glissandi (after Metastaseis)", lines: [
      "C     STRING GLISSANDI, AFTER METASTASEIS (1953-54)",
      "C     IN BARS 309 TO 314 OF METASTASEIS THE STRINGS PLAY GLISSANDI THAT",
      "C     XENAKIS DREW AS STRAIGHT LINES ON A GRAPH OF PITCH AGAINST TIME.",
      "C     HERE EACH LINE MOVES IN SEMITONE STEPS FROM ITS NOTE IN A CLUSTER",
      "C     TO ITS NOTE IN A WIDE CHORD, ALL OVER THE SAME SPAN OF PULSES.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE 1 (2I5): NUMBER OF LINES (UP TO 8), PULSES",
      "C     LINE 2 (8I5): START NOTES. LINE 3 (8I5): END NOTES.",
      "      DIMENSION NS(8), NE(8)",
      "      READ (5,10) NL, NP",
      "   10 FORMAT (2I5)",
      "      READ (5,11) NS(1),NS(2),NS(3),NS(4),NS(5),NS(6),NS(7),NS(8)",
      "      READ (5,11) NE(1),NE(2),NE(3),NE(4),NE(5),NE(6),NE(7),NE(8)",
      "   11 FORMAT (8I5)",
      "      WRITE (6,15) NL, NP",
      "   15 FORMAT (1H1,'STRING GLISSANDI,',I2,' LINES OVER',I4,' PULSES'/",
      "     1       1H0,'  LINE  FROM    TO  STEPS')",
      "      NC = 0",
      "      DO 60 L = 1, NL",
      "      LAST = NS(L)",
      "      ITS = 0",
      "      NSTEP = 0",
      "      DO 50 J = 1, NP",
      "C     THE STRAIGHT LINE FROM NS TO NE, ROUNDED TO THE NEAREST SEMITONE",
      "      X = FLOAT(NS(L)) + FLOAT((NE(L) - NS(L))*J)/FLOAT(NP)",
      "      NOTE = INT(X + 0.5)",
      "      IF (J .EQ. NP) GO TO 40",
      "      IF (NOTE .EQ. LAST) GO TO 50",
      "   40 LEN = J - ITS",
      "      WRITE (7,45) ITS, LAST, LEN, 4",
      "   45 FORMAT (4I5)",
      "      NC = NC + 1",
      "      NSTEP = NSTEP + 1",
      "      LAST = NOTE",
      "      ITS = J",
      "   50 CONTINUE",
      "      WRITE (6,55) L, NS(L), NE(L), NSTEP",
      "   55 FORMAT (1X,4I6)",
      "   60 CONTINUE",
      "      WRITE (6,65) NC",
      "   65 FORMAT (1H0,I5,' NOTES WRITTEN')",
      "      STOP",
      "      END",
      "    6   24",
      "   60   61   62   63   64   65",
      "   86   40   79   47   93   36"
    ] },
    { name: "Brownian melody (after Mikka)", lines: [
      "C     BROWNIAN MELODY, AFTER MIKKA (1971)",
      "C     MIKKA, FOR SOLO VIOLIN, IS ONE UNBROKEN GLISSANDO WHOSE PATH",
      "C     XENAKIS DREW FROM A RANDOM WALK, LIKE A PARTICLE KNOCKED ABOUT BY",
      "C     COLLISIONS. HERE THE WALK MOVES BY UP TO MAXS SEMITONES EACH",
      "C     PULSE AND BOUNCES OFF THE EDGES OF A RANGE, AND A HELD NOTE LASTS",
      "C     UNTIL THE WALK MOVES ON.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE (6I5): SEED, PULSES (UP TO 400), FIRST NOTE, LOWEST",
      "C        NOTE, HIGHEST NOTE, LARGEST STEP MAXS",
      "      DIMENSION NT(416)",
      "      READ (5,10) IX, NS, NOTE, LOW, NHI, MAXS",
      "   10 FORMAT (6I5)",
      "      DO 15 K = 1, 416",
      "      NT(K) = 0",
      "   15 CONTINUE",
      "      LAST = NOTE",
      "      ITS = 0",
      "      NE = 0",
      "      NMIN = NOTE",
      "      NMAX = NOTE",
      "      NT(1) = NOTE",
      "      DO 50 K = 1, NS",
      "      IX = MOD(171*IX, 30269)",
      "      NOTE = NOTE + MOD(IX, 2*MAXS + 1) - MAXS",
      "C     THE EDGES OF THE RANGE REFLECT THE WALK",
      "      IF (NOTE .LT. LOW) NOTE = 2*LOW - NOTE",
      "      IF (NOTE .GT. NHI) NOTE = 2*NHI - NOTE",
      "      IF (K .LT. NS) NT(K+1) = NOTE",
      "      IF (NOTE .LT. NMIN) NMIN = NOTE",
      "      IF (NOTE .GT. NMAX) NMAX = NOTE",
      "      IF (NOTE .EQ. LAST .AND. K .LT. NS) GO TO 50",
      "      LEN = K - ITS",
      "      WRITE (7,40) ITS, LAST, LEN, 6",
      "   40 FORMAT (4I5)",
      "      NE = NE + 1",
      "      LAST = NOTE",
      "      ITS = K",
      "   50 CONTINUE",
      "      WRITE (6,55) NS, NE, NMIN, NMAX",
      "   55 FORMAT (1H1,'BROWNIAN MELODY OVER',I4,' PULSES,',I4,' NOTES'/",
      "     1       1H0,'LOWEST',I4,'   HIGHEST',I4/1H0,'PULSE  NOTES')",
      "      DO 70 K = 1, NS, 16",
      "      IP = K - 1",
      "      WRITE (6,60) IP,NT(K),NT(K+1),NT(K+2),NT(K+3),NT(K+4),NT(K+5),",
      "     1 NT(K+6),NT(K+7),NT(K+8),NT(K+9),NT(K+10),NT(K+11),NT(K+12),",
      "     2 NT(K+13),NT(K+14),NT(K+15)",
      "   70 CONTINUE",
      "   60 FORMAT (1X,I5,16I4)",
      "      STOP",
      "      END",
      " 1971  128   67   55   96    2"
    ] },
    { name: "Arborescence (after Evryali)", lines: [
      "C     ARBORESCENCE, AFTER EVRYALI (1973)",
      "C     IN EVRYALI, FOR PIANO, XENAKIS GREW LINES THAT BRANCH OUT OF OTHER",
      "C     LINES, SO THAT ONE LINE CAN BECOME AS MANY AS SIX. HERE A LINE",
      "C     CLIMBS OR FALLS BY ONE OR TWO SEMITONES EACH PULSE, NOW AND THEN",
      "C     BENDS, AND AT RANDOM SPLITS IN TWO, UP TO SIX LINES AT ONCE.",
      "C     EACH NOTE GOES TO THE OUTPUT AS ONE LINE (4I5): TIME IN",
      "C     PULSES, NOTE (MIDI NUMBER, 60 IS MIDDLE C), LENGTH IN PULSES,",
      "C     LOUDNESS 1 TO 9. THE PLAYER PLAYS THE OUTPUT.",
      "C     DATA LINE (4I5): SEED, PULSES, FIRST NOTE, CHANCE OF A BRANCH",
      "C        EACH PULSE, IN PERCENT",
      "      DIMENSION NT(6), IS(6), ION(6)",
      "      READ (5,10) IX, NP, NOTE, IPB",
      "   10 FORMAT (4I5)",
      "      DO 15 L = 1, 6",
      "      ION(L) = 0",
      "   15 CONTINUE",
      "      NT(1) = NOTE",
      "      IS(1) = 1",
      "      ION(1) = 1",
      "      NL = 1",
      "      NE = 0",
      "      WRITE (6,20) NP",
      "   20 FORMAT (1H1,'ARBORESCENCE OVER',I4,' PULSES'/1H0,'PULSE  EVENT')",
      "      DO 80 J = 1, NP",
      "      IT = J - 1",
      "      DO 60 L = 1, 6",
      "      IF (ION(L) .EQ. 0) GO TO 60",
      "      WRITE (7,30) IT, NT(L), 1, 5",
      "   30 FORMAT (4I5)",
      "      NE = NE + 1",
      "C     NOW AND THEN THE LINE BENDS: A NEW STEP OF -2, -1, 1 OR 2",
      "      IX = MOD(171*IX, 30269)",
      "      IF (MOD(IX, 100) .GE. 12) GO TO 40",
      "      IX = MOD(171*IX, 30269)",
      "      IS(L) = MOD(IX, 4) - 2",
      "      IF (IS(L) .GE. 0) IS(L) = IS(L) + 1",
      "   40 NT(L) = NT(L) + IS(L)",
      "      IF (NT(L) .LT. 36) IS(L) = IABS(IS(L))",
      "      IF (NT(L) .GT. 96) IS(L) = -IABS(IS(L))",
      "      IF (NT(L) .LT. 36) NT(L) = 36",
      "      IF (NT(L) .GT. 96) NT(L) = 96",
      "   60 CONTINUE",
      "C     A BRANCH: A FREE LINE STARTS FROM A LIVE ONE, GOING ITS OWN WAY",
      "      IF (NL .GE. 6) GO TO 80",
      "      IX = MOD(171*IX, 30269)",
      "      IF (MOD(IX, 100) .GE. IPB) GO TO 80",
      "      IX = MOD(171*IX, 30269)",
      "      LP = MOD(IX, 6) + 1",
      "   65 IF (ION(LP) .EQ. 0) LP = 1",
      "      NEW = 0",
      "      DO 70 L = 1, 6",
      "      IF (NEW .EQ. 0 .AND. ION(L) .EQ. 0) NEW = L",
      "   70 CONTINUE",
      "      ION(NEW) = 1",
      "      NT(NEW) = NT(LP)",
      "      IS(NEW) = -IS(LP)",
      "      NL = NL + 1",
      "      WRITE (6,75) IT, LP, NEW, NL",
      "   75 FORMAT (1X,I5,'  LINE',I2,' BRANCHES INTO LINE',I2,',',I2,",
      "     1       ' LINES')",
      "   80 CONTINUE",
      "      WRITE (6,85) NE",
      "   85 FORMAT (1H0,I5,' NOTES')",
      "      STOP",
      "      END",
      " 1974   64   60   18"
    ] }
  ]
};
