[
  { id: "the-best-pinhole", name: "The best pinhole (after Petzval and Rayleigh)", cards: [
    "C     THE BEST PINHOLE (AFTER PETZVAL AND RAYLEIGH)",
    "C     A CAMERA WITH NO LENS. EACH POINT OF THE SCENE THROWS A PATCH OF",
    "C     LIGHT ABOUT THE SIZE OF THE HOLE, SO A SMALLER HOLE GIVES A",
    "C     SHARPER PICTURE, UNTIL DIFFRACTION SPREADS THE LIGHT AGAIN. FOR",
    "C     EACH DISTANCE F FROM HOLE TO FILM THERE IS A BEST HOLE. PETZVAL",
    "C     (1857) GAVE D = SQRT(2 F L) AND RAYLEIGH (1891) D = 2 SQRT(F L),",
    "C     FOR LIGHT OF WAVELENGTH L. THE DECK PRINTS BOTH, THE F-NUMBER",
    "C     F/D OF RAYLEIGH'S HOLE, HOW MANY STOPS IT LIES PAST THE STOP OF",
    "C     THE SUNNY SIXTEEN RULE, AND THE EXPOSURE IT NEEDS: THE RULE'S",
    "C     1/ASA SECOND TIMES (F-NUMBER/STOP) SQUARED.",
    "C     DATA CARDS: (I5,I5,F5.0) WAVELENGTH IN NANOMETRES (550 IS GREEN,",
    "C     WHERE THE EYE IS KEENEST), FILM SPEED (ASA), AND THE STOP THE",
    "C     RULE GIVES FOR THE LIGHT (16 FOR BRIGHT SUN);",
    "C     (10F5.0) UP TO TEN DISTANCES FROM HOLE TO FILM IN MM. A BLANK",
    "C     FIELD ENDS THE LIST.",
    "C     TRY BLUE LIGHT (450), OR ASA 25 IN OPEN SHADE (25 AND 4).",
    "      DIMENSION FL(10)",
    "      READ (5,10) IWL, IASA, S",
    "   10 FORMAT (2I5,F5.0)",
    "      READ (5,11) FL(1),FL(2),FL(3),FL(4),FL(5),FL(6),FL(7),FL(8),",
    "     1 FL(9),FL(10)",
    "   11 FORMAT (10F5.0)",
    "C     THE WAVELENGTH IN MILLIMETRES",
    "      WL = FLOAT(IWL)/1000000.0",
    "      IS = INT(S + 0.5)",
    "      IF (S .LT. 10.0) WRITE (6,12) IWL, IASA, S, IASA",
    "      IF (S .GE. 10.0) WRITE (6,13) IWL, IASA, IS, IASA",
    "   12 FORMAT (1H1,'THE BEST PINHOLE'/1H0,'LIGHT OF',I4,' NM, FILM OF ',",
    "     1 'ASA',I5,'. THE RULE GIVES F/',F3.1,' AT 1/',I4,' SECOND.')",
    "   13 FORMAT (1H1,'THE BEST PINHOLE'/1H0,'LIGHT OF',I4,' NM, FILM OF ',",
    "     1 'ASA',I5,'. THE RULE GIVES F/',I2,' AT 1/',I4,' SECOND.')",
    "      WRITE (6,14)",
    "   14 FORMAT (1H0,'PETZVAL, 1857:   D = SQRT(2 F L)'/",
    "     1 1H ,'RAYLEIGH, 1891:  D = 2 SQRT(F L)'/1H0,",
    "     2 '   HOLE TO     BEST HOLE (MM)     F-NUMBER     STOPS',",
    "     3 '     EXPOSURE'/1H ,",
    "     4 '   FILM (MM)  PETZVAL  RAYLEIGH  (RAYLEIGH)  PAST RULE',",
    "     5 '    (SECONDS)'/1H )",
    "      N = 0",
    "      DO 50 I = 1, 10",
    "      F = FL(I)",
    "      IF (F .LE. 0.0) GO TO 60",
    "      N = N + 1",
    "      DP = SQRT(2.0*F*WL)",
    "      DR = 2.0*SQRT(F*WL)",
    "      FN = F/DR",
    "      ST = 2.0*ALOG(FN/S)/ALOG(2.0)",
    "      T = (FN/S)**2/FLOAT(IASA)",
    "      IFL = INT(F + 0.5)",
    "      IFN = INT(FN + 0.5)",
    "      WRITE (6,40) IFL, DP, DR, IFN, ST, T",
    "   40 FORMAT (1X,I9,F12.3,F9.3,6X,'F/',I4,F11.1,F13.2)",
    "   50 CONTINUE",
    "   60 IF (N .EQ. 0) WRITE (6,62)",
    "   62 FORMAT (1X,'   NO DISTANCES ON THE CARD.')",
    "      WRITE (6,65)",
    "   65 FORMAT (1H0,'THE HOLE GROWS ONLY AS THE SQUARE ROOT OF THE ',",
    "     1 'DISTANCE: FOUR TIMES AS'/1H ,'LONG A CAMERA TAKES TWICE THE ',",
    "     2 'HOLE, TWICE THE F-NUMBER AND FOUR TIMES'/1H ,'THE EXPOSURE. ',",
    "     3 'EXPOSURES OF A SECOND OR MORE NEED STILL MORE, AS FILM'/",
    "     4 1H ,'LOSES SPEED IN DIM LIGHT (RECIPROCITY FAILURE).')",
    "      STOP",
    "      END",
    "  550  100  16.",
    "   25   50   75  100  150  200  300  500"
  ] },
  { id: "the-thin-lens", name: "The thin lens (image distances and a ray diagram)", cards: [
    "C     THE THIN LENS: IMAGE DISTANCES, MAGNIFICATION AND A RAY DIAGRAM",
    "C     A LENS OF FOCAL LENGTH F BRINGS THE LIGHT FROM A POINT U IN FRONT",
    "C     OF IT TO A POINT V BEHIND IT, WHERE 1/F = 1/U + 1/V. THE IMAGE IS",
    "C     INVERTED AND M = V/U TIMES THE SIZE OF THE SUBJECT. TO FOCUS ON A",
    "C     NEAR SUBJECT THE LENS MOVES FORWARD BY V - F, AND THE LIGHT IS",
    "C     SPREAD OVER A LARGER IMAGE, SO THE EXPOSURE MUST GROW BY (1+M)**2.",
    "C     THE DECK PRINTS THE ANGLE OF VIEW ACROSS THE FRAME, 2 ATAN(D/2F),",
    "C     A TABLE FOR EIGHT DISTANCES, AND A RAY DIAGRAM FOR ONE: A RAY",
    "C     PARALLEL TO THE AXIS BENDS THROUGH THE FOCAL POINT BEHIND THE",
    "C     LENS, A RAY THROUGH THE CENTRE GOES STRAIGHT ON, AND A RAY THROUGH",
    "C     THE FOCAL POINT IN FRONT LEAVES PARALLEL. ALL THREE MEET AT THE",
    "C     TIP OF THE IMAGE.",
    "C     DATA CARDS: (3F10.0) FOCAL LENGTH IN MM, DIAGONAL OF THE FRAME IN",
    "C     MM (43.27 FOR 24 BY 36), HEIGHT OF THE SUBJECT IN MM;",
    "C     (8F10.0) EIGHT SUBJECT DISTANCES IN MM, MEASURED FROM THE LENS;",
    "C     (F10.0) THE SUBJECT DISTANCE FOR THE RAY DIAGRAM (MORE THAN F).",
    "C     TRY A DIAGRAM AT 100 (TWICE F, LIFE SIZE) OR AT 70 (MAGNIFIED).",
    "      DIMENSION U(8), G(72,25), P(72), SX(11), SY(11), TX(11), TY(11)",
    "      READ (5,10) F, DIAG, H",
    "      READ (5,11) U(1),U(2),U(3),U(4),U(5),U(6),U(7),U(8)",
    "      READ (5,10) UD",
    "   10 FORMAT (3F10.0)",
    "   11 FORMAT (8F10.0)",
    "      PI = 3.14159",
    "      AOV = 2.0*ATAN(DIAG/(2.0*F))*180.0/PI",
    "      IH = INT(H + 0.5)",
    "      WRITE (6,12) F, DIAG, AOV, IH",
    "   12 FORMAT (1H1,'THE THIN LENS'/1H0,'FOCAL LENGTH',F7.1,' MM. ',",
    "     1 'ACROSS A FRAME WITH A DIAGONAL OF',F6.2,' MM'/1H ,",
    "     2 'IT SEES',F6.1,' DEGREES. THE SUBJECT IS',I6,' MM TALL.'/",
    "     3 1H0,'1/F = 1/U + 1/V    M = V/U'/1H0,",
    "     4 '   SUBJECT    IMAGE    LENS MOVED  MAGNIFI-   SCALE   ',",
    "     5 ' IMAGE OF   EXPOSURE'/1H ,",
    "     6 '   DISTANCE  DISTANCE   FORWARD     CATION            ',",
    "     7 ' SUBJECT     FACTOR'/1H ,",
    "     8 '    U (MM)    V (MM)   V-F (MM)      V/U              ',",
    "     9 '   (MM)    (1+M)**2  STOPS'/1H )",
    "      DO 30 I = 1, 8",
    "      IU = INT(U(I) + 0.5)",
    "      IF (U(I) .GT. F) GO TO 25",
    "      WRITE (6,22) IU",
    "   22 FORMAT (1X,I9,'    NO REAL IMAGE: THE SUBJECT IS INSIDE THE ',",
    "     1 'FOCAL LENGTH')",
    "      GO TO 30",
    "   25 V = 1.0/(1.0/F - 1.0/U(I))",
    "      EM = V/U(I)",
    "      RN = U(I)/V",
    "      SZ = H*EM",
    "      EF = (1.0 + EM)**2",
    "      ST = ALOG(EF)/ALOG(2.0)",
    "      WRITE (6,26) IU, V, V-F, EM, RN, SZ, EF, ST",
    "   26 FORMAT (1X,I9,F10.2,F10.2,F12.4,'   1:',F6.1,F10.1,F10.2,F7.2)",
    "   30 CONTINUE",
    "C     THE RAY DIAGRAM. THE SUBJECT IS DRAWN ONE UNIT TALL AND THE IMAGE",
    "C     M UNITS, BELOW THE AXIS. THE LENS STANDS AT X = 0.",
    "      IF (UD .GT. F) GO TO 40",
    "      WRITE (6,35)",
    "   35 FORMAT (1H0,'NO RAY DIAGRAM: THE SUBJECT IS INSIDE THE FOCAL ',",
    "     1 'LENGTH, AND THE LENS'/1H ,'MAKES NO REAL IMAGE.')",
    "      STOP",
    "   40 VD = 1.0/(1.0/F - 1.0/UD)",
    "      EM = VD/UD",
    "      XL = -UD - 0.05*(UD + VD)",
    "      XR = VD + 0.25*(UD + VD)",
    "      YM = 1.15*AMAX1(1.0, EM)",
    "      DO 42 J = 1, 25",
    "      DO 41 I = 1, 72",
    "      G(I,J) = 0.0",
    "   41 CONTINUE",
    "   42 CONTINUE",
    "C     THE AXIS, DASHED",
    "      DO 43 I = 1, 72, 3",
    "      G(I,13) = 1.0",
    "   43 CONTINUE",
    "C     THE SEGMENTS: LENS, SUBJECT, IMAGE, THE THREE RAYS, TWO TICKS",
    "      SX(1) = 0.0",
    "      SY(1) = -YM",
    "      TX(1) = 0.0",
    "      TY(1) = YM",
    "      SX(2) = -UD",
    "      SY(2) = 0.0",
    "      TX(2) = -UD",
    "      TY(2) = 1.0",
    "      SX(3) = VD",
    "      SY(3) = 0.0",
    "      TX(3) = VD",
    "      TY(3) = -EM",
    "      SX(4) = -UD",
    "      SY(4) = 1.0",
    "      TX(4) = 0.0",
    "      TY(4) = 1.0",
    "      SX(5) = 0.0",
    "      SY(5) = 1.0",
    "      TX(5) = XR",
    "      TY(5) = 1.0 - XR/F",
    "      SX(6) = -UD",
    "      SY(6) = 1.0",
    "      TX(6) = XR",
    "      TY(6) = -XR/UD",
    "      SX(7) = -UD",
    "      SY(7) = 1.0",
    "      TX(7) = 0.0",
    "      TY(7) = -EM",
    "      SX(8) = 0.0",
    "      SY(8) = -EM",
    "      TX(8) = XR",
    "      TY(8) = -EM",
    "      SX(9) = -F",
    "      SY(9) = -YM/12.0",
    "      TX(9) = -F",
    "      TY(9) = YM/12.0",
    "      SX(10) = F",
    "      SY(10) = -YM/12.0",
    "      TX(10) = F",
    "      TY(10) = YM/12.0",
    "      DO 50 K = 1, 10",
    "      DO 48 L = 0, 400",
    "      Q = FLOAT(L)/400.0",
    "      X = SX(K) + Q*(TX(K) - SX(K))",
    "      Y = SY(K) + Q*(TY(K) - SY(K))",
    "      IC = INT((X - XL)/(XR - XL)*71.0 + 1.5)",
    "      IR = INT(13.5 - Y/YM*12.0)",
    "      IF (IC .LT. 1 .OR. IC .GT. 72) GO TO 48",
    "      IF (IR .LT. 1 .OR. IR .GT. 25) GO TO 48",
    "      G(IC,IR) = 1.0",
    "   48 CONTINUE",
    "   50 CONTINUE",
    "      IUD = INT(UD + 0.5)",
    "      WRITE (6,52) IUD",
    "   52 FORMAT (1H0,'RAY DIAGRAM FOR A SUBJECT AT',I7,' MM'/1H )",
    "      DO 60 J = 1, 25",
    "      DO 55 I = 1, 72",
    "      P(I) = G(I,J)",
    "   55 CONTINUE",
    "      WRITE (6,58) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68),P(69),P(70),",
    "     7 P(71),P(72)",
    "   58 FORMAT (1X,72F1.0)",
    "   60 CONTINUE",
    "      KO = INT((-UD - XL)/(XR - XL)*71.0 + 1.5)",
    "      KL = INT((0.0 - XL)/(XR - XL)*71.0 + 1.5)",
    "      KI = INT((VD - XL)/(XR - XL)*71.0 + 1.5)",
    "      WRITE (6,62) KO, KL, KI, VD, EM",
    "   62 FORMAT (1H0,'THE SUBJECT STANDS AT COLUMN',I3,', THE LENS AT ',",
    "     1 'COLUMN',I3,' AND THE IMAGE'/1H ,'AT COLUMN',I3,'. THE TICKS ',",
    "     2 'ON THE AXIS ARE THE FOCAL POINTS, ONE FOCAL'/1H ,'LENGTH ',",
    "     3 'EITHER SIDE OF THE LENS. THE IMAGE FALLS',F8.2,' MM BEHIND'/",
    "     4 1H ,'THE LENS, INVERTED, AT',F7.3,' TIMES THE SIZE.')",
    "      STOP",
    "      END",
    "      50.0     43.27    1750.0",
    "     500.0    1000.0    2000.0    3000.0   10000.0     200.0     100.0      40.0",
    "     150.0"
  ] },
  { id: "sunny-sixteen", name: "Sunny sixteen (an exposure table)", cards: [
    "C     SUNNY SIXTEEN: AN EXPOSURE TABLE BY RECIPROCITY",
    "C     THE RULE: IN BRIGHT SUN, SET THE LENS TO F/16 AND THE SHUTTER TO",
    "C     ONE OVER THE FILM SPEED. FOR DULLER LIGHT OPEN THE LENS: F/11 FOR",
    "C     A LIGHT OVERCAST, F/8 OVERCAST, F/5.6 HEAVY OVERCAST, F/4 OPEN",
    "C     SHADE; F/22 FOR SAND OR SNOW. THE DECK TURNS THE RULE INTO AN",
    "C     EXPOSURE VALUE, EV = LOG2(N*N/T) FOR STOP N AND TIME T SECONDS,",
    "C     AND PRINTS EVERY STOP AGAINST EVERY SPEED. EACH STEP ACROSS OR",
    "C     DOWN IS ONE STOP, HALF OR DOUBLE THE LIGHT, SO EQUAL VALUES RUN",
    "C     ON A DIAGONAL: THAT IS RECIPROCITY. THEN IT LISTS THE SETTINGS",
    "C     THAT GIVE THE SAME EXPOSURE AS THE RULE.",
    "C     DATA CARD (I5,F5.0): FILM SPEED (ASA, 6 TO 3200), THE STOP THE",
    "C     RULE GIVES FOR THE LIGHT (22, 16, 11, 8, 5.6 OR 4)",
    "C     TRY ASA 400 IN OPEN SHADE (4), OR ASA 25 ON SNOW (22).",
    "      DIMENSION FN(10), IT(11), IEV(11)",
    "      READ (5,10) IASA, STOP",
    "   10 FORMAT (I5,F5.0)",
    "C     THE NOMINAL STOPS AND SPEEDS. STOP K IS K STOPS FROM F/1, AND",
    "C     SPEED J IS J STOPS FROM 1 SECOND, SO EV IS SIMPLY K + J",
    "      FN(1) = 1.4",
    "      FN(2) = 2.0",
    "      FN(3) = 2.8",
    "      FN(4) = 4.0",
    "      FN(5) = 5.6",
    "      FN(6) = 8.0",
    "      FN(7) = 11.0",
    "      FN(8) = 16.0",
    "      FN(9) = 22.0",
    "      FN(10) = 32.0",
    "      IT(1) = 1",
    "      IT(2) = 2",
    "      IT(3) = 4",
    "      IT(4) = 8",
    "      IT(5) = 15",
    "      IT(6) = 30",
    "      IT(7) = 60",
    "      IT(8) = 125",
    "      IT(9) = 250",
    "      IT(10) = 500",
    "      IT(11) = 1000",
    "C     THE RULE: STOP N AT 1/ASA SECOND",
    "      E = ALOG(STOP*STOP*FLOAT(IASA))/ALOG(2.0)",
    "      KEV = INT(E + 0.5)",
    "      IF (STOP .LT. 10.0) WRITE (6,15) IASA, STOP, IASA, E, KEV",
    "      IF (STOP .GE. 10.0) WRITE (6,16) IASA, INT(STOP), IASA, E, KEV",
    "   15 FORMAT (1H1,'SUNNY SIXTEEN'/1H0,'FILM SPEED ASA',I5/1H ,",
    "     1 'THE RULE GIVES F/',F3.1,' AT 1/',I4,' SECOND, EV',F6.2,",
    "     2 ', CALL IT EV',I3)",
    "   16 FORMAT (1H1,'SUNNY SIXTEEN'/1H0,'FILM SPEED ASA',I5/1H ,",
    "     1 'THE RULE GIVES F/',I2,' AT 1/',I4,' SECOND, EV',F6.2,",
    "     2 ', CALL IT EV',I3)",
    "      IF (STOP .GT. 19.0) WRITE (6,21)",
    "      IF (STOP .GT. 13.0 .AND. STOP .LE. 19.0) WRITE (6,22)",
    "      IF (STOP .GT. 9.5 .AND. STOP .LE. 13.0) WRITE (6,23)",
    "      IF (STOP .GT. 6.8 .AND. STOP .LE. 9.5) WRITE (6,24)",
    "      IF (STOP .GT. 4.8 .AND. STOP .LE. 6.8) WRITE (6,25)",
    "      IF (STOP .LE. 4.8) WRITE (6,26)",
    "   21 FORMAT (1H ,'THE LIGHT: SAND OR SNOW IN BRIGHT SUN')",
    "   22 FORMAT (1H ,'THE LIGHT: BRIGHT SUN, SHADOWS SHARP')",
    "   23 FORMAT (1H ,'THE LIGHT: LIGHT OVERCAST, SHADOWS SOFT')",
    "   24 FORMAT (1H ,'THE LIGHT: OVERCAST, SHADOWS BARELY THERE')",
    "   25 FORMAT (1H ,'THE LIGHT: HEAVY OVERCAST, NO SHADOWS')",
    "   26 FORMAT (1H ,'THE LIGHT: OPEN SHADE, OR SUNSET')",
    "      WRITE (6,30)",
    "   30 FORMAT (1H0,'EXPOSURE VALUE OF EVERY SETTING'/1H0,12X,",
    "     1 'SHUTTER, 1/N SECOND'/1H ,'  STOP    ',",
    "     2 '     1     2     4     8    15    30    60   125   250   500',",
    "     3 '  1000'/1H )",
    "      DO 40 K = 1, 10",
    "      DO 35 J = 1, 11",
    "      IEV(J) = K + J - 1",
    "   35 CONTINUE",
    "      IF (K .LT. 7) WRITE (6,36) FN(K), IEV(1),IEV(2),IEV(3),IEV(4),",
    "     1 IEV(5),IEV(6),IEV(7),IEV(8),IEV(9),IEV(10),IEV(11)",
    "      IF (K .GE. 7) WRITE (6,37) INT(FN(K)), IEV(1),IEV(2),IEV(3),",
    "     1 IEV(4),IEV(5),IEV(6),IEV(7),IEV(8),IEV(9),IEV(10),IEV(11)",
    "   36 FORMAT (1X,'  F/',F3.1,3X,11I6)",
    "   37 FORMAT (1X,'  F/',I2,4X,11I6)",
    "   40 CONTINUE",
    "      WRITE (6,45) KEV",
    "   45 FORMAT (1H0,'THE SAME EXPOSURE AS THE RULE, EV',I3,':'/1H )",
    "      N = 0",
    "      DO 60 K = 1, 10",
    "      J = KEV - K + 1",
    "      IF (J .LT. 1 .OR. J .GT. 11) GO TO 60",
    "      N = N + 1",
    "      IF (K .GE. 7) GO TO 55",
    "      IF (J .EQ. 1) WRITE (6,51) FN(K)",
    "      IF (J .GT. 1) WRITE (6,52) FN(K), IT(J)",
    "      GO TO 60",
    "   55 IF (J .EQ. 1) WRITE (6,53) INT(FN(K))",
    "      IF (J .GT. 1) WRITE (6,54) INT(FN(K)), IT(J)",
    "   60 CONTINUE",
    "   51 FORMAT (1X,'  F/',F3.1,'  AT  1 SECOND')",
    "   52 FORMAT (1X,'  F/',F3.1,'  AT  1/',I4,' SECOND')",
    "   53 FORMAT (1X,'  F/',I2,1X,'  AT  1 SECOND')",
    "   54 FORMAT (1X,'  F/',I2,1X,'  AT  1/',I4,' SECOND')",
    "      IF (N .EQ. 0) WRITE (6,62)",
    "   62 FORMAT (1X,'  NONE: THE LIGHT IS OFF THE TABLE')",
    "      WRITE (6,65) N",
    "   65 FORMAT (1H0,I3,' SETTINGS, ONE EXPOSURE. A WIDER STOP GIVES LESS',",
    "     1 ' DEPTH OF FIELD;'/1H ,'    A SHORTER TIME STOPS MORE MOTION.')",
    "      STOP",
    "      END",
    "  100  16."
  ] },
  { id: "depth-of-field", name: "Depth of field (near, far and hyperfocal)", cards: [
    "C     DEPTH OF FIELD: NEAR AND FAR LIMITS, HYPERFOCAL DISTANCE, AND",
    "C     THE AIRY DISC, FOR ONE LENS ACROSS ITS STOPS",
    "C     A LENS FOCUSES EXACTLY AT ONE DISTANCE S. NEARER AND FARTHER",
    "C     POINTS MAKE SMALL DISCS ON THE FILM, AND THEY PASS FOR SHARP",
    "C     WHILE THE DISCS ARE NO WIDER THAN THE CIRCLE OF CONFUSION C",
    "C     (ABOUT 0.03 MM FOR A 24 BY 36 FRAME). FOR FOCAL LENGTH F AND STOP",
    "C     N, THE HYPERFOCAL DISTANCE IS H = F*F/(N*C) + F; FOCUSED THERE,",
    "C     EVERYTHING FROM H/2 TO INFINITY IS SHARP. FOCUSED AT S, THE NEAR",
    "C     LIMIT IS S(H-F)/(H+S-2F) AND THE FAR LIMIT S(H-F)/(H-S), OR",
    "C     INFINITY WHEN S IS H OR MORE. STOPPING DOWN DEEPENS THE FIELD,",
    "C     BUT DIFFRACTION SPREADS EVERY POINT INTO AN AIRY DISC 2.44 L N",
    "C     ACROSS, AND WHEN THAT IS WIDER THAN C NOTHING IS QUITE SHARP.",
    "C     THE STOPS ARE THE MARKED ONES; BESIDE EACH IS THE EXACT POWER OF",
    "C     THE SQUARE ROOT OF 2 THAT IT ROUNDS. A CHART SHOWS THE ZONE OF",
    "C     SHARPNESS AT EVERY STOP ON A SCALE OF DISTANCE.",
    "C     DATA CARD (4F10.0): FOCAL LENGTH IN MM, CIRCLE OF CONFUSION IN",
    "C     MM, DISTANCE FOCUSED ON IN METRES (MORE THAN F), WAVELENGTH IN NM",
    "C     TRY FOCUSING AT THE HYPERFOCAL DISTANCE OF F/8 (10.47), OR A",
    "C     300 MM LENS ON 8 BY 10 INCH FILM: C = 0.2, FOCUSED AT 6 METRES.",
    "      DIMENSION FS(12), P(68)",
    "      READ (5,10) F, C, SM, WNM",
    "   10 FORMAT (4F10.0)",
    "      FS(1) = 1.4",
    "      FS(2) = 2.0",
    "      FS(3) = 2.8",
    "      FS(4) = 4.0",
    "      FS(5) = 5.6",
    "      FS(6) = 8.0",
    "      FS(7) = 11.0",
    "      FS(8) = 16.0",
    "      FS(9) = 22.0",
    "      FS(10) = 32.0",
    "      FS(11) = 45.0",
    "      FS(12) = 64.0",
    "      S = SM*1000.0",
    "      WL = WNM/1000000.0",
    "      IWL = INT(WNM + 0.5)",
    "      WRITE (6,12) F, C, SM, IWL",
    "   12 FORMAT (1H1,'DEPTH OF FIELD'/1H0,'FOCAL LENGTH',F7.1,' MM, ',",
    "     1 'CIRCLE OF CONFUSION',F6.3,' MM,'/1H ,'FOCUSED AT',F7.2,",
    "     2 ' M, LIGHT OF',I4,' NM.'/1H0,'H = F*F/(N*C) + F',4X,",
    "     3 'NEAR = S(H-F)/(H+S-2F)',4X,'FAR = S(H-F)/(H-S)'/1H ,",
    "     4 'AIRY DISC, ACROSS TO THE FIRST DARK RING = 2.44 L N'/1H0,",
    "     5 '   STOP   SQRT(2)  HYPER-     NEAR     FAR     DEPTH    ',",
    "     6 'AIRY DISC'/1H ,",
    "     7 '          TO THE   FOCAL     LIMIT    LIMIT      OF     ',",
    "     8 'DIAMETER'/1H ,",
    "     9 '          POWER K  H (M)      (M)      (M)   FIELD (M)    (MM)'/",
    "     1 1H )",
    "      IF (S .GT. F) GO TO 20",
    "      WRITE (6,14)",
    "   14 FORMAT (1X,'THE LENS CANNOT FOCUS NEARER THAN ITS FOCAL LENGTH.')",
    "      STOP",
    "   20 DO 40 K = 1, 12",
    "      EN = FS(K)",
    "      EX = SQRT(2.0)**K",
    "      H = F*F/(EN*C) + F",
    "      DN = S*(H - F)/(H + S - 2.0*F)",
    "      AD = 2.44*WL*EN",
    "      IF (EN .LT. 10.0) WRITE (6,22) EN",
    "      IF (EN .GE. 10.0) WRITE (6,23) INT(EN)",
    "   22 FORMAT (1X,'   F/',F3.1)",
    "   23 FORMAT (1X,'   F/',I2)",
    "      IF (S .GE. H) GO TO 30",
    "      DF = S*(H - F)/(H - S)",
    "      WRITE (6,25) EX, H/1000.0, DN/1000.0, DF/1000.0,",
    "     1 (DF - DN)/1000.0, AD",
    "   25 FORMAT (1H+,8X,F8.2,F9.2,F9.2,F9.2,F9.2,F11.4)",
    "      GO TO 35",
    "   30 WRITE (6,32) EX, H/1000.0, DN/1000.0, AD",
    "   32 FORMAT (1H+,8X,F8.2,F9.2,F9.2,' INFINITY',' INFINITY',F11.4)",
    "   35 IF (AD .GT. C) WRITE (6,37)",
    "   37 FORMAT (1H+,65X,'WIDER THAN C')",
    "   40 CONTINUE",
    "      ENC = C/(2.44*WL)",
    "      WRITE (6,42) ENC",
    "   42 FORMAT (1H0,'THE AIRY DISC GROWS AS WIDE AS THE CIRCLE OF ',",
    "     1 'CONFUSION AT F/',F5.1,'.'/1H ,'PAST IT, STOPPING DOWN ',",
    "     2 'DEEPENS THE FIELD BUT SOFTENS EVERYTHING IN IT.')",
    "C     THE CHART: 61 COLUMNS FOR 0.5 TO 50 METRES, 30 TO A DECADE, THEN",
    "C     A GAP AND FOUR COLUMNS FOR INFINITY",
    "      WRITE (6,50)",
    "   50 FORMAT (1H0,'THE ZONE OF SHARPNESS, ON A SCALE OF METRES'/1H )",
    "      DO 70 K = 1, 12",
    "      EN = FS(K)",
    "      H = F*F/(EN*C) + F",
    "      DN = S*(H - F)/(H + S - 2.0*F)",
    "      DF = 1.0E9",
    "      IF (S .LT. H) DF = S*(H - F)/(H - S)",
    "      DO 60 J = 1, 68",
    "      P(J) = 0.0",
    "      IF (J .GT. 61) GO TO 55",
    "C     A COLUMN IS INKED IF ANY PART OF ITS SPAN OF DISTANCE IS SHARP",
    "      DLO = 500.0*10.0**((FLOAT(J) - 1.5)/30.0)",
    "      DHI = 500.0*10.0**((FLOAT(J) - 0.5)/30.0)",
    "      IF (DLO .LE. DF .AND. DHI .GE. DN) P(J) = 1.0",
    "      GO TO 60",
    "   55 IF (J .GE. 65 .AND. S .GE. H) P(J) = 1.0",
    "   60 CONTINUE",
    "      IF (EN .LT. 10.0) WRITE (6,22) EN",
    "      IF (EN .GE. 10.0) WRITE (6,23) INT(EN)",
    "      WRITE (6,65) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68)",
    "   65 FORMAT (1H+,10X,68F1.0)",
    "   70 CONTINUE",
    "      DO 72 J = 1, 68",
    "      P(J) = 0.0",
    "   72 CONTINUE",
    "      JF = INT(30.0*ALOG10(S/500.0) + 1.5)",
    "      IF (JF .GE. 1 .AND. JF .LE. 61) P(JF) = 1.0",
    "      WRITE (6,74)",
    "   74 FORMAT (1X,'   FOCUS')",
    "      WRITE (6,65) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68)",
    "      WRITE (6,76)",
    "   76 FORMAT (1X,10X,'0.5      1        2           5',",
    "     1 '        10       20         50   INF')",
    "      STOP",
    "      END",
    "      50.0      0.03       3.0     550.0"
  ] },
  { id: "spherical-aberration", name: "Spherical aberration (a ray trace through one lens)", cards: [
    "C     SPHERICAL ABERRATION: A RAY TRACE THROUGH ONE PLANO-CONVEX LENS",
    "C     A LENS WITH SPHERICAL FACES BENDS THE RAYS NEAR ITS RIM TOO MUCH,",
    "C     SO THEY CROSS THE AXIS SHORT OF THE FOCUS OF THE RAYS NEAR THE",
    "C     CENTRE. THE DECK TRACES PARALLEL RAYS AT TEN HEIGHTS THROUGH A",
    "C     LENS WITH ONE CURVED FACE AND ONE FLAT, BY THE LAW OF REFRACTION",
    "C     (SIN I = N SIN R AT EACH FACE), FIRST WITH THE CURVED FACE TO THE",
    "C     LIGHT AND THEN THE FLAT FACE. IT PRINTS WHERE EACH RAY CROSSES",
    "C     THE AXIS, MEASURED FROM THE BACK FACE, AND HOW FAR SHORT OF THE",
    "C     PARAXIAL FOCUS (THE FOCUS OF RAYS CLOSE TO THE AXIS) IT FALLS,",
    "C     FINDS THE SMALLEST SPOT (THE CIRCLE OF LEAST CONFUSION), AND",
    "C     DRAWS THE BEAM NEAR THE FOCUS FOR BOTH WAYS ROUND, ON ONE SCALE.",
    "C     DATA CARD (4F10.0,I5): RADIUS OF THE CURVED FACE IN MM, INDEX OF",
    "C     THE GLASS, THICKNESS AT THE CENTRE IN MM, HALF THE CLEAR APERTURE",
    "C     IN MM, NUMBER OF RAYS (2 TO 10)",
    "C     TRY HALF THE APERTURE (6.25, TWO STOPS DOWN): THE ABERRATION",
    "C     FALLS TO A QUARTER. OR GLASS OF INDEX 1.7, WITH A RADIUS OF 70.",
    "      DIMENSION XC(2,10), XE(2,10), YE(2,10), TA(2,10), YR(10),",
    "     1 PF(2), SA(2), BX(2), BW(2), G(72,21), P(72)",
    "      READ (5,10) R, EN, T, H, NR",
    "   10 FORMAT (4F10.0,I5)",
    "      IF (NR .LT. 2) NR = 2",
    "      IF (NR .GT. 10) NR = 10",
    "      F = R/(EN - 1.0)",
    "      FNO = F/(2.0*H)",
    "      SAG = R - SQRT(R*R - H*H)",
    "      WRITE (6,12) R, EN, T, H, F, FNO",
    "   12 FORMAT (1H1,'SPHERICAL ABERRATION'/1H0,'A PLANO-CONVEX LENS: ',",
    "     1 'RADIUS',F7.2,' MM, INDEX',F6.3,', THICKNESS',F6.2,' MM,'/1H ,",
    "     2 'CLEAR APERTURE',F6.2,' MM EITHER SIDE OF THE AXIS.'/1H ,",
    "     3 'FOCAL LENGTH R/(N-1) =',F7.2,' MM, WORKING AT F/',F4.1,'.')",
    "      IF (SAG .LT. T) GO TO 15",
    "      WRITE (6,14)",
    "   14 FORMAT (1H0,'THE LENS IS TOO THIN FOR ITS APERTURE: ITS EDGE ',",
    "     1 'WOULD HAVE NO THICKNESS.')",
    "      STOP",
    "C     K = 1: CURVED FACE TO THE LIGHT. K = 2: FLAT FACE TO THE LIGHT.",
    "C     X IS MEASURED FROM THE BACK FACE OF THE LENS. RAY 0 IS PARAXIAL.",
    "   15 DO 40 K = 1, 2",
    "      DO 38 J = 0, NR",
    "      Y = H*FLOAT(J)/FLOAT(NR)",
    "      IF (J .EQ. 0) Y = H/1000.0",
    "      IF (K .EQ. 2) GO TO 25",
    "C     CURVED FACE FIRST: REFRACT AT THE SPHERE, CROSS THE GLASS,",
    "C     REFRACT AGAIN AT THE FLAT",
    "      X1 = R - SQRT(R*R - Y*Y)",
    "      SI = Y/R",
    "      SR = SI/EN",
    "      TH = ATAN(SI/SQRT(1.0 - SI*SI)) - ATAN(SR/SQRT(1.0 - SR*SR))",
    "      Y2 = Y - (T - X1)*SIN(TH)/COS(TH)",
    "      SP = EN*SIN(TH)",
    "      PH = ATAN(SP/SQRT(1.0 - SP*SP))",
    "      XX = 0.0",
    "      YY = Y2",
    "      TT = SIN(PH)/COS(PH)",
    "      GO TO 30",
    "C     FLAT FACE FIRST: STRAIGHT THROUGH THE FLAT, REFRACT AT THE SPHERE",
    "   25 X2 = SQRT(R*R - Y*Y) - R",
    "      SI = Y/R",
    "      SB = EN*SI",
    "      IF (SB .LT. 1.0) GO TO 27",
    "      WRITE (6,26) Y",
    "   26 FORMAT (1H0,'A RAY AT',F6.2,' MM IS REFLECTED INSIDE THE GLASS. ',",
    "     1 'MAKE THE APERTURE SMALLER.')",
    "      STOP",
    "   27 TH = ATAN(SB/SQRT(1.0 - SB*SB)) - ATAN(SI/SQRT(1.0 - SI*SI))",
    "      XX = X2",
    "      YY = Y",
    "      TT = SIN(TH)/COS(TH)",
    "   30 XL = XX + YY/TT",
    "      IF (J .EQ. 0) PF(K) = XL",
    "      IF (J .EQ. 0) GO TO 38",
    "      YR(J) = Y",
    "      XC(K,J) = XL",
    "      XE(K,J) = XX",
    "      YE(K,J) = YY",
    "      TA(K,J) = TT",
    "   38 CONTINUE",
    "      SA(K) = PF(K) - XC(K,NR)",
    "   40 CONTINUE",
    "      WRITE (6,42)",
    "   42 FORMAT (1H0,'   RAY      ZONE     CURVED FACE TO THE LIGHT     ',",
    "     1 'FLAT FACE TO THE LIGHT'/1H ,",
    "     2 '  HEIGHT             CROSSES AXIS   SHORT OF    ',",
    "     3 'CROSSES AXIS   SHORT OF'/1H ,",
    "     4 '   (MM)               BEHIND (MM)  FOCUS (MM)    ',",
    "     5 'BEHIND (MM)  FOCUS (MM)'/1H )",
    "      WRITE (6,44) PF(1), PF(2)",
    "   44 FORMAT (1X,'  PARAXIAL',11X,F10.3,14X,F12.3)",
    "      DO 48 J = 1, NR",
    "      Z = F/(2.0*YR(J))",
    "      WRITE (6,46) YR(J), Z, XC(1,J), PF(1) - XC(1,J), XC(2,J),",
    "     1 PF(2) - XC(2,J)",
    "   46 FORMAT (1X,F8.2,'    F/',F5.1,F10.3,F12.3,F15.3,F12.3)",
    "   48 CONTINUE",
    "C     THE SMALLEST SPOT: THE WIDTH OF THE BEAM, SEARCHED ALONG THE AXIS",
    "C     BETWEEN THE MARGINAL CROSSING AND THE PARAXIAL FOCUS",
    "      DO 60 K = 1, 2",
    "      BW(K) = 1.0E9",
    "      DO 58 L = 0, 400",
    "      X = XC(K,NR) + SA(K)*FLOAT(L)/400.0",
    "      W = 0.0",
    "      DO 55 J = 1, NR",
    "      W = AMAX1(W, ABS(YE(K,J) - (X - XE(K,J))*TA(K,J)))",
    "   55 CONTINUE",
    "      IF (W .GE. BW(K)) GO TO 58",
    "      BW(K) = W",
    "      BX(K) = X",
    "   58 CONTINUE",
    "   60 CONTINUE",
    "      RAT = SA(2)/SA(1)",
    "      WRITE (6,62) SA(1), BX(1), 2.0*BW(1), SA(2), BX(2), 2.0*BW(2), RAT",
    "   62 FORMAT (1H0,'CURVED FACE TO THE LIGHT: THE RIM RAYS FALL',F7.3,",
    "     1 ' MM SHORT. THE SMALLEST'/1H ,'SPOT IS',F8.3,' MM BEHIND THE ',",
    "     2 'LENS AND',F7.4,' MM ACROSS.'/1H ,'FLAT FACE TO THE LIGHT:   ',",
    "     3 'THE RIM RAYS FALL',F7.3,' MM SHORT. THE SMALLEST'/1H ,",
    "     4 'SPOT IS',F8.3,' MM BEHIND THE LENS AND',F7.4,' MM ACROSS.'/",
    "     5 1H0,'TURNED THE WRONG WAY ROUND, THE LENS HAS',F5.1,",
    "     6 ' TIMES THE ABERRATION.')",
    "C     THE PICTURES: THE BEAM SEEN FROM THE SIDE, INKED FROM ITS TOP RAY",
    "C     TO ITS BOTTOM RAY IN EVERY COLUMN, SO THAT IT NARROWS TO A WAIST,",
    "C     THE SMALLEST SPOT, AND OPENS AGAIN. EACH WINDOW ENDS A LITTLE PAST",
    "C     ITS OWN PARAXIAL FOCUS AND IS 1.3 TIMES THE LARGER ABERRATION",
    "C     LONG, SO THE TWO ARE DRAWN TO ONE SCALE, ACROSS AND UP.",
    "      SL = 1.3*AMAX1(SA(1), SA(2))",
    "      YM = 0.0",
    "      DO 66 K = 1, 2",
    "      DO 65 J = 1, NR",
    "      X = PF(K) - 0.85*SL",
    "      YM = AMAX1(YM, ABS(YE(K,J) - (X - XE(K,J))*TA(K,J)))",
    "      X = PF(K) + 0.15*SL",
    "      YM = AMAX1(YM, ABS(YE(K,J) - (X - XE(K,J))*TA(K,J)))",
    "   65 CONTINUE",
    "   66 CONTINUE",
    "      DO 90 K = 1, 2",
    "      X0 = PF(K) - 0.85*SL",
    "      DO 72 I = 1, 72",
    "      X = X0 + SL*(FLOAT(I) - 0.5)/72.0",
    "      W = 0.0",
    "      DO 69 J = 1, NR",
    "      W = AMAX1(W, ABS(YE(K,J) - (X - XE(K,J))*TA(K,J)))",
    "   69 CONTINUE",
    "      DO 71 J = 1, 21",
    "      G(I,J) = 0.0",
    "      IF (ABS(FLOAT(J - 11)) .LE. W/YM*10.0) G(I,J) = 1.0",
    "   71 CONTINUE",
    "   72 CONTINUE",
    "      IF (K .EQ. 1) WRITE (6,74)",
    "      IF (K .EQ. 2) WRITE (6,75)",
    "   74 FORMAT (1H0,'CURVED FACE TO THE LIGHT'/1H )",
    "   75 FORMAT (1H0,'FLAT FACE TO THE LIGHT'/1H )",
    "      DO 80 J = 1, 21",
    "      DO 77 I = 1, 72",
    "      P(I) = G(I,J)",
    "   77 CONTINUE",
    "      WRITE (6,78) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68),P(69),P(70),",
    "     7 P(71),P(72)",
    "   78 FORMAT (1X,72F1.0)",
    "   80 CONTINUE",
    "      KB = INT((BX(K) - X0)/SL*72.0) + 1",
    "      KP = INT(0.85*72.0) + 1",
    "      WRITE (6,82) X0, X0 + SL, KP, KB",
    "   82 FORMAT (1X,'FROM',F8.2,' TO',F8.2,' MM BEHIND THE LENS. ',",
    "     1 'PARAXIAL FOCUS AT COLUMN',I3,','/1H ,'SMALLEST SPOT AT ',",
    "     2 'COLUMN',I3,'.')",
    "   90 CONTINUE",
    "      STOP",
    "      END",
    "      50.0       1.5       5.0      12.5   10"
  ] }
]
