[
  { id: "the-house-of-dust", name: "The house of dust (after Knowles and Tenney)", cards: [
    "C     THE HOUSE OF DUST, AFTER ALISON KNOWLES AND JAMES TENNEY (1967)",
    "C     KNOWLES WROTE FOUR LISTS: WHAT A HOUSE IS MADE OF, WHERE IT",
    "C     STANDS, HOW IT IS LIT AND WHO LIVES IN IT. TENNEY HELPED HER",
    "C     PROGRAM A COMPUTER IN FORTRAN TO DRAW ONE LINE FROM EACH LIST,",
    "C     BY CHANCE, FOR EVERY STANZA. THE LISTS HERE ARE HERS, SHORTENED:",
    "C     14 MATERIALS, 16 PLACES, 4 LIGHTS AND 14 KINDS OF INHABITANT,",
    "C     WHICH MAKE 12544 DIFFERENT HOUSES.",
    "C     DATA CARD (2I5): SEED (1 TO 30268), NUMBER OF STANZAS",
    "C     A NEW DATA CARD IS PUNCHED AT THE END, HOLDING THE SEED THE RUN",
    "C     HAS REACHED: PUT IT AFTER END IN PLACE OF THE OLD ONE AND THE",
    "C     NEXT RUN PRINTS THE STANZAS THAT FOLLOW.",
    "C     TRY THE SEED 10763: ITS FIRST HOUSE IS THE ONE BUILT AT CALARTS.",
    "      READ (5,10) IX, N",
    "   10 FORMAT (2I5)",
    "      WRITE (6,15)",
    "   15 FORMAT (1H1,'A HOUSE OF DUST')",
    "      DO 90 K = 1, N",
    "C     WHAT IT IS MADE OF",
    "      IX = MOD(171*IX, 30269)",
    "      I = MOD(IX, 14) + 1",
    "      IF (I .EQ. 1) WRITE (6,101)",
    "      IF (I .EQ. 2) WRITE (6,102)",
    "      IF (I .EQ. 3) WRITE (6,103)",
    "      IF (I .EQ. 4) WRITE (6,104)",
    "      IF (I .EQ. 5) WRITE (6,105)",
    "      IF (I .EQ. 6) WRITE (6,106)",
    "      IF (I .EQ. 7) WRITE (6,107)",
    "      IF (I .EQ. 8) WRITE (6,108)",
    "      IF (I .EQ. 9) WRITE (6,109)",
    "      IF (I .EQ. 10) WRITE (6,110)",
    "      IF (I .EQ. 11) WRITE (6,111)",
    "      IF (I .EQ. 12) WRITE (6,112)",
    "      IF (I .EQ. 13) WRITE (6,113)",
    "      IF (I .EQ. 14) WRITE (6,114)",
    "C     WHERE IT STANDS",
    "      IX = MOD(171*IX, 30269)",
    "      I = MOD(IX, 16) + 1",
    "      IF (I .EQ. 1) WRITE (6,201)",
    "      IF (I .EQ. 2) WRITE (6,202)",
    "      IF (I .EQ. 3) WRITE (6,203)",
    "      IF (I .EQ. 4) WRITE (6,204)",
    "      IF (I .EQ. 5) WRITE (6,205)",
    "      IF (I .EQ. 6) WRITE (6,206)",
    "      IF (I .EQ. 7) WRITE (6,207)",
    "      IF (I .EQ. 8) WRITE (6,208)",
    "      IF (I .EQ. 9) WRITE (6,209)",
    "      IF (I .EQ. 10) WRITE (6,210)",
    "      IF (I .EQ. 11) WRITE (6,211)",
    "      IF (I .EQ. 12) WRITE (6,212)",
    "      IF (I .EQ. 13) WRITE (6,213)",
    "      IF (I .EQ. 14) WRITE (6,214)",
    "      IF (I .EQ. 15) WRITE (6,215)",
    "      IF (I .EQ. 16) WRITE (6,216)",
    "C     HOW IT IS LIT",
    "      IX = MOD(171*IX, 30269)",
    "      I = MOD(IX, 4) + 1",
    "      IF (I .EQ. 1) WRITE (6,301)",
    "      IF (I .EQ. 2) WRITE (6,302)",
    "      IF (I .EQ. 3) WRITE (6,303)",
    "      IF (I .EQ. 4) WRITE (6,304)",
    "C     WHO LIVES IN IT",
    "      IX = MOD(171*IX, 30269)",
    "      I = MOD(IX, 14) + 1",
    "      IF (I .EQ. 1) WRITE (6,401)",
    "      IF (I .EQ. 2) WRITE (6,402)",
    "      IF (I .EQ. 3) WRITE (6,403)",
    "      IF (I .EQ. 4) WRITE (6,404)",
    "      IF (I .EQ. 5) WRITE (6,405)",
    "      IF (I .EQ. 6) WRITE (6,406)",
    "      IF (I .EQ. 7) WRITE (6,407)",
    "      IF (I .EQ. 8) WRITE (6,408)",
    "      IF (I .EQ. 9) WRITE (6,409)",
    "      IF (I .EQ. 10) WRITE (6,410)",
    "      IF (I .EQ. 11) WRITE (6,411)",
    "      IF (I .EQ. 12) WRITE (6,412)",
    "      IF (I .EQ. 13) WRITE (6,413)",
    "      IF (I .EQ. 14) WRITE (6,414)",
    "   90 CONTINUE",
    "      PUNCH 95, IX, N",
    "   95 FORMAT (2I5,5X,'THE NEXT STANZAS OF A HOUSE OF DUST')",
    "      STOP",
    "  101 FORMAT (1H0,'A HOUSE OF SAND')",
    "  102 FORMAT (1H0,'A HOUSE OF DUST')",
    "  103 FORMAT (1H0,'A HOUSE OF LEAVES')",
    "  104 FORMAT (1H0,'A HOUSE OF PAPER')",
    "  105 FORMAT (1H0,'A HOUSE OF TIN')",
    "  106 FORMAT (1H0,'A HOUSE OF ROOTS')",
    "  107 FORMAT (1H0,'A HOUSE OF BRICK')",
    "  108 FORMAT (1H0,'A HOUSE OF STONE')",
    "  109 FORMAT (1H0,'A HOUSE OF DISCARDED CLOTHING')",
    "  110 FORMAT (1H0,'A HOUSE OF GLASS')",
    "  111 FORMAT (1H0,'A HOUSE OF STEEL')",
    "  112 FORMAT (1H0,'A HOUSE OF PLASTIC')",
    "  113 FORMAT (1H0,'A HOUSE OF MUD')",
    "  114 FORMAT (1H0,'A HOUSE OF BROKEN DISHES')",
    "  201 FORMAT (1X,'     IN A GREEN, MOSSY TERRAIN')",
    "  202 FORMAT (1X,'     IN AN OVERPOPULATED AREA')",
    "  203 FORMAT (1X,'     BY THE SEA')",
    "  204 FORMAT (1X,'     BY AN ABANDONED LAKE')",
    "  205 FORMAT (1X,'     IN A DESERTED FACTORY')",
    "  206 FORMAT (1X,'     IN DENSE WOODS')",
    "  207 FORMAT (1X,'     IN JAPAN')",
    "  208 FORMAT (1X,'     AMONG SMALL HILLS')",
    "  209 FORMAT (1X,'     AMONG HIGH MOUNTAINS')",
    "  210 FORMAT (1X,'     ON AN ISLAND')",
    "  211 FORMAT (1X,'     ON OPEN GROUND')",
    "  212 FORMAT (1X,'     IN A COLD, WINDY CLIMATE')",
    "  213 FORMAT (1X,'     IN A PLACE WITH BOTH HEAVY RAIN AND BRIGHT SUN')",
    "  214 FORMAT (1X,'     IN A DESERTED AIRPORT')",
    "  215 FORMAT (1X,'     IN A METROPOLIS')",
    "  216 FORMAT (1X,'     UNDERWATER')",
    "  301 FORMAT (1X,'     USING CANDLES')",
    "  302 FORMAT (1X,'     USING ALL AVAILABLE LIGHTING')",
    "  303 FORMAT (1X,'     USING ELECTRICITY')",
    "  304 FORMAT (1X,'     USING NATURAL LIGHT')",
    "  401 FORMAT (1X,'     INHABITED BY PEOPLE WHO SLEEP VERY LITTLE')",
    "  402 FORMAT (1X,'     INHABITED BY VEGETARIANS')",
    "  403 FORMAT (1X,'     INHABITED BY HORSES AND BIRDS')",
    "  404 FORMAT (1X,'     INHABITED BY CHILDREN AND OLD PEOPLE')",
    "  405 FORMAT (1X,'     INHABITED BY VARIOUS BIRDS AND FISH')",
    "  406 FORMAT (1X,'     INHABITED BY LOVERS')",
    "  407 FORMAT (1X,'     INHABITED BY PEOPLE WHO ENJOY EATING TOGETHER')",
    "  408 FORMAT (1X,'     INHABITED BY PEOPLE WHO EAT A GREAT DEAL')",
    "  409 FORMAT (1X,'     INHABITED BY COLLECTORS OF ALL TYPES')",
    "  410 FORMAT (1X,'     INHABITED BY FRIENDS AND ENEMIES')",
    "  411 FORMAT (1X,",
    "     1'     INHABITED BY PEOPLE WHO SLEEP ALMOST ALL THE TIME')",
    "  412 FORMAT (1X,'     INHABITED BY VERY TALL PEOPLE')",
    "  413 FORMAT (1X,'     INHABITED BY FISHERMEN AND FAMILIES')",
    "  414 FORMAT (1X,'     INHABITED BY PEOPLE WHO LOVE TO READ')",
    "      END",
    " 1967    8"
  ] },
  { id: "event-cards", name: "Event cards (a deck by chance, after George Brecht)", cards: [
    "C     EVENT CARDS: A DECK OF EVENT SCORES DRAWN BY CHANCE",
    "C     AFTER GEORGE BRECHT, WHO FROM 1959 WROTE EVENTS AS A FEW WORDS",
    "C     ON A SMALL CARD. EACH CARD HERE HAS A TITLE, AN OBJECT FROM THE",
    "C     ROOM, AND ONE TO THREE LINES DRAWN FROM A LIST OF TWENTY, NEVER",
    "C     THE SAME LINE TWICE ON A CARD. THE CARDS ARE PRINTED IN FRAMES,",
    "C     AND EACH IS ALSO PUNCHED, TITLE AND LINES, ONE CARD TO A LINE,",
    "C     SO THE STACKER HOLDS THE DECK READY TO HAND OUT AND PERFORM.",
    "C     DATA CARD (2I5): SEED (1 TO 30268), NUMBER OF CARDS (1 TO 50)",
    "      DIMENSION IL(3)",
    "      READ (5,10) IX, N",
    "   10 FORMAT (2I5)",
    "      WRITE (6,15)",
    "   15 FORMAT (1H1,'EVENT CARDS, DRAWN BY CHANCE')",
    "      DO 90 K = 1, N",
    "C     THE TITLE",
    "      IX = MOD(171*IX, 30269)",
    "      IT = MOD(IX, 12) + 1",
    "C     HOW MANY LINES, AND WHICH: A LINE ALREADY ON THE CARD IS DRAWN",
    "C     AGAIN",
    "      IX = MOD(171*IX, 30269)",
    "      NL = MOD(IX, 3) + 1",
    "      DO 30 L = 1, NL",
    "   20 IX = MOD(171*IX, 30269)",
    "      J = MOD(IX, 20) + 1",
    "      IF (L .EQ. 1) GO TO 30",
    "      LL = L - 1",
    "      DO 25 M = 1, LL",
    "      IF (IL(M) .EQ. J) GO TO 20",
    "   25 CONTINUE",
    "   30 IL(L) = J",
    "C     PRINT THE CARD IN ITS FRAME, AND PUNCH IT",
    "      WRITE (6,40)",
    "      WRITE (6,41)",
    "      IF (IT .EQ. 1) WRITE (6,101)",
    "      IF (IT .EQ. 2) WRITE (6,102)",
    "      IF (IT .EQ. 3) WRITE (6,103)",
    "      IF (IT .EQ. 4) WRITE (6,104)",
    "      IF (IT .EQ. 5) WRITE (6,105)",
    "      IF (IT .EQ. 6) WRITE (6,106)",
    "      IF (IT .EQ. 7) WRITE (6,107)",
    "      IF (IT .EQ. 8) WRITE (6,108)",
    "      IF (IT .EQ. 9) WRITE (6,109)",
    "      IF (IT .EQ. 10) WRITE (6,110)",
    "      IF (IT .EQ. 11) WRITE (6,111)",
    "      IF (IT .EQ. 12) WRITE (6,112)",
    "      IF (IT .EQ. 1) PUNCH 101",
    "      IF (IT .EQ. 2) PUNCH 102",
    "      IF (IT .EQ. 3) PUNCH 103",
    "      IF (IT .EQ. 4) PUNCH 104",
    "      IF (IT .EQ. 5) PUNCH 105",
    "      IF (IT .EQ. 6) PUNCH 106",
    "      IF (IT .EQ. 7) PUNCH 107",
    "      IF (IT .EQ. 8) PUNCH 108",
    "      IF (IT .EQ. 9) PUNCH 109",
    "      IF (IT .EQ. 10) PUNCH 110",
    "      IF (IT .EQ. 11) PUNCH 111",
    "      IF (IT .EQ. 12) PUNCH 112",
    "      WRITE (6,42)",
    "      WRITE (6,41)",
    "      DO 60 L = 1, NL",
    "      J = IL(L)",
    "      IF (J .EQ. 1) WRITE (6,201)",
    "      IF (J .EQ. 2) WRITE (6,202)",
    "      IF (J .EQ. 3) WRITE (6,203)",
    "      IF (J .EQ. 4) WRITE (6,204)",
    "      IF (J .EQ. 5) WRITE (6,205)",
    "      IF (J .EQ. 6) WRITE (6,206)",
    "      IF (J .EQ. 7) WRITE (6,207)",
    "      IF (J .EQ. 8) WRITE (6,208)",
    "      IF (J .EQ. 9) WRITE (6,209)",
    "      IF (J .EQ. 10) WRITE (6,210)",
    "      IF (J .EQ. 11) WRITE (6,211)",
    "      IF (J .EQ. 12) WRITE (6,212)",
    "      IF (J .EQ. 13) WRITE (6,213)",
    "      IF (J .EQ. 14) WRITE (6,214)",
    "      IF (J .EQ. 15) WRITE (6,215)",
    "      IF (J .EQ. 16) WRITE (6,216)",
    "      IF (J .EQ. 17) WRITE (6,217)",
    "      IF (J .EQ. 18) WRITE (6,218)",
    "      IF (J .EQ. 19) WRITE (6,219)",
    "      IF (J .EQ. 20) WRITE (6,220)",
    "      IF (J .EQ. 1) PUNCH 201",
    "      IF (J .EQ. 2) PUNCH 202",
    "      IF (J .EQ. 3) PUNCH 203",
    "      IF (J .EQ. 4) PUNCH 204",
    "      IF (J .EQ. 5) PUNCH 205",
    "      IF (J .EQ. 6) PUNCH 206",
    "      IF (J .EQ. 7) PUNCH 207",
    "      IF (J .EQ. 8) PUNCH 208",
    "      IF (J .EQ. 9) PUNCH 209",
    "      IF (J .EQ. 10) PUNCH 210",
    "      IF (J .EQ. 11) PUNCH 211",
    "      IF (J .EQ. 12) PUNCH 212",
    "      IF (J .EQ. 13) PUNCH 213",
    "      IF (J .EQ. 14) PUNCH 214",
    "      IF (J .EQ. 15) PUNCH 215",
    "      IF (J .EQ. 16) PUNCH 216",
    "      IF (J .EQ. 17) PUNCH 217",
    "      IF (J .EQ. 18) PUNCH 218",
    "      IF (J .EQ. 19) PUNCH 219",
    "      IF (J .EQ. 20) PUNCH 220",
    "      WRITE (6,42)",
    "   60 CONTINUE",
    "      WRITE (6,41)",
    "      WRITE (6,43) K",
    "      WRITE (6,42)",
    "      WRITE (6,44)",
    "   90 CONTINUE",
    "      WRITE (6,45) N",
    "      STOP",
    "   40 FORMAT (1H0,'+------------------------------------+')",
    "   41 FORMAT (1X,'|',36X,'|')",
    "   42 FORMAT (1H+,'|',36X,'|')",
    "   43 FORMAT (1X,28X,'NO.',I4)",
    "   44 FORMAT (1X,'+------------------------------------+')",
    "   45 FORMAT (1H0,I3,' CARDS PUNCHED. PERFORM ANY OF THEM.')",
    "  101 FORMAT (1X,'   WATER EVENT')",
    "  102 FORMAT (1X,'   LAMP EVENT')",
    "  103 FORMAT (1X,'   CHAIR EVENT')",
    "  104 FORMAT (1X,'   DOOR EVENT')",
    "  105 FORMAT (1X,'   WINDOW EVENT')",
    "  106 FORMAT (1X,'   CLOCK EVENT')",
    "  107 FORMAT (1X,'   PAPER EVENT')",
    "  108 FORMAT (1X,'   CARD EVENT')",
    "  109 FORMAT (1X,'   PRINTER EVENT')",
    "  110 FORMAT (1X,'   TAPE EVENT')",
    "  111 FORMAT (1X,'   TABLE EVENT')",
    "  112 FORMAT (1X,'   SHOE EVENT')",
    "  201 FORMAT (1X,'        . ON.')",
    "  202 FORMAT (1X,'        . OFF.')",
    "  203 FORMAT (1X,'        . OPEN.')",
    "  204 FORMAT (1X,'        . SHUT.')",
    "  205 FORMAT (1X,'        . FILL.')",
    "  206 FORMAT (1X,'        . EMPTY.')",
    "  207 FORMAT (1X,'        . DRIPPING.')",
    "  208 FORMAT (1X,'        . ONCE.')",
    "  209 FORMAT (1X,'        . AGAIN.')",
    "  210 FORMAT (1X,'        . COUNT THEM.')",
    "  211 FORMAT (1X,'        . LISTEN.')",
    "  212 FORMAT (1X,'        . TURN IT OVER.')",
    "  213 FORMAT (1X,'        . IN THE DARK.')",
    "  214 FORMAT (1X,'        . SLOWLY.')",
    "  215 FORMAT (1X,'        . LEAVE THE ROOM.')",
    "  216 FORMAT (1X,'        . FOLD.')",
    "  217 FORMAT (1X,'        . PUNCH A HOLE.')",
    "  218 FORMAT (1X,'        . WAIT.')",
    "  219 FORMAT (1X,'        . EXIT.')",
    "  220 FORMAT (1X,'        . STOP.')",
    "      END",
    " 1959    6"
  ] },
  { id: "to-be-held-for-a-long-time", name: "To be held for a long time (after La Monte Young)", cards: [
    "C     TO BE HELD FOR A LONG TIME, AFTER LA MONTE YOUNG",
    "C     THE WHOLE SCORE OF YOUNG'S COMPOSITION 1960 #7 IS A B AND THE",
    "C     F SHARP ABOVE IT, AND THE WORDS TO BE HELD FOR A LONG TIME.",
    "C     FIRST THE DECK WORKS OUT THE INTERVAL: THE TWO FREQUENCIES (A",
    "C     ABOVE MIDDLE C IS 440 HZ), ITS SIZE IN CENTS, THE NEAREST SIMPLE",
    "C     RATIO, AND THE TWO HARMONICS THAT NEARLY MEET AND BEAT. THEN EACH",
    "C     PLAYER HOLDS A NOTE IN BOWS OF 3 TO 9 SECONDS, EACH BOW A LITTLE",
    "C     LOUDER OR SOFTER BY CHANCE, SO THE SOUND NEVER STOPS. EACH BOW IS",
    "C     PUNCHED AS A TAPE CARD (4I5): TIME IN PULSES, NOTE (MIDI NUMBER,",
    "C     60 IS MIDDLE C), LENGTH IN PULSES, LOUDNESS 1 TO 9. AT 120 BEATS",
    "C     A MINUTE A PULSE IS AN EIGHTH OF A SECOND.",
    "C     DATA CARD 1 (3I5): SEED, LENGTH IN PULSES (72 TO 9999), PLAYERS",
    "C        (2 TO 6). THEN ONE CARD (I5) PER PLAYER: THE NOTE HE OR SHE",
    "C        HOLDS. THE FIRST TWO PLAYERS' NOTES ARE THE INTERVAL.",
    "C     THE CHART: ONE ROW PER PLAYER, 72 COLUMNS FOR THE WHOLE LENGTH;",
    "C     A DIGIT IS THE LOUDNESS OF THE BOW SOUNDING, AN ASTERISK BELOW",
    "C     MARKS A CHANGE OF BOW. COLUMNS PAST THE END SHOW 0; A LENGTH OF",
    "C     72 TIMES A WHOLE NUMBER FILLS THE ROW.",
    "      DIMENSION NOTE(6), IC(6,72), B(72), IB(72)",
    "      REAL B",
    "      READ (5,10) IX, LEN, NP",
    "   10 FORMAT (3I5)",
    "      DO 12 K = 1, NP",
    "      READ (5,11) NOTE(K)",
    "   12 CONTINUE",
    "   11 FORMAT (I5)",
    "      WRITE (6,15)",
    "   15 FORMAT (1H1,'TO BE HELD FOR A LONG TIME'/1H0,",
    "     1'  NOTE    FREQUENCY')",
    "      NL = MIN0(NOTE(1), NOTE(2))",
    "      NH = MAX0(NOTE(1), NOTE(2))",
    "      FL = 440.0*2.0**(FLOAT(NL-69)/12.0)",
    "      FH = 440.0*2.0**(FLOAT(NH-69)/12.0)",
    "      WRITE (6,16) NL, FL",
    "      WRITE (6,16) NH, FH",
    "   16 FORMAT (1X,I6,F11.2,' HZ')",
    "      CENTS = 1200.0*ALOG(FH/FL)/ALOG(2.0)",
    "C     THE TWO HARMONICS, ONE OF EACH NOTE, UP TO THE EIGHTH, THAT LIE",
    "C     CLOSEST TOGETHER",
    "      BEAT = 99999.0",
    "      DO 20 I = 1, 8",
    "      DO 20 J = 1, 8",
    "      D = ABS(FLOAT(I)*FL - FLOAT(J)*FH)",
    "      IF (D .GE. BEAT) GO TO 20",
    "      BEAT = D",
    "      IH = I",
    "      JH = J",
    "   20 CONTINUE",
    "      PURE = 1200.0*ALOG(FLOAT(IH)/FLOAT(JH))/ALOG(2.0)",
    "      HL = FLOAT(IH)*FL",
    "      HH = FLOAT(JH)*FH",
    "      WRITE (6,25) CENTS, IH, JH, PURE",
    "   25 FORMAT (1H0,'THE INTERVAL IS',F8.2,",
    "     1' CENTS. ITS NEAREST SIMPLE RATIO IS',I2,':',I1,",
    "     2', WHICH WOULD BE',F8.2,' CENTS.')",
    "      WRITE (6,26) IH, HL, JH, HH, BEAT",
    "   26 FORMAT (1X,'HARMONIC',I2,' OF THE LOW NOTE IS',F8.2,",
    "     1' HZ AND HARMONIC',I2,' OF THE HIGH NOTE IS',F8.2,' HZ:'/1X,",
    "     2'THEY BEAT',F6.2,' TIMES A SECOND.')",
    "C     THE BOWS",
    "      IW = (LEN + 71)/72",
    "      NB = 0",
    "      WRITE (6,30) LEN, IW",
    "   30 FORMAT (1H0,'THE PLAYERS, OVER',I5,' PULSES,',I3,",
    "     1' PULSES TO A COLUMN')",
    "      DO 70 K = 1, NP",
    "      DO 35 L = 1, 72",
    "      IB(L) = 0",
    "   35 B(L) = 0.0",
    "      IT = 0",
    "   40 IX = MOD(171*IX, 30269)",
    "      IS = 24 + MOD(IX, 49)",
    "      IF (IT + IS .GT. LEN) IS = LEN - IT",
    "      IX = MOD(171*IX, 30269)",
    "      LOUD = 3 + MOD(IX, 5)",
    "      PUNCH 45, IT, NOTE(K), IS, LOUD",
    "   45 FORMAT (4I5)",
    "      NB = NB + 1",
    "      L1 = IT/IW + 1",
    "      L2 = (IT + IS - 1)/IW + 1",
    "      B(L1) = 1.0",
    "      DO 50 L = L1, L2",
    "      IF ((L-1)*IW .GE. IT) IC(K,L) = LOUD",
    "   50 CONTINUE",
    "      IT = IT + IS",
    "      IF (IT .LT. LEN) GO TO 40",
    "      NC = (LEN - 1)/IW + 1",
    "      WRITE (6,55) K, NOTE(K)",
    "   55 FORMAT (1H0,'PLAYER',I2,', NOTE',I4)",
    "      WRITE (6,56) IC(K,1),IC(K,2),IC(K,3),IC(K,4),IC(K,5),IC(K,6),",
    "     1IC(K,7),IC(K,8),IC(K,9),IC(K,10),IC(K,11),IC(K,12),IC(K,13),",
    "     2IC(K,14),IC(K,15),IC(K,16),IC(K,17),IC(K,18),IC(K,19),IC(K,20),",
    "     3IC(K,21),IC(K,22),IC(K,23),IC(K,24),IC(K,25),IC(K,26),IC(K,27),",
    "     4IC(K,28),IC(K,29),IC(K,30),IC(K,31),IC(K,32),IC(K,33),IC(K,34),",
    "     5IC(K,35),IC(K,36),IC(K,37),IC(K,38),IC(K,39),IC(K,40),IC(K,41),",
    "     6IC(K,42),IC(K,43),IC(K,44),IC(K,45),IC(K,46),IC(K,47),IC(K,48),",
    "     7IC(K,49),IC(K,50),IC(K,51),IC(K,52),IC(K,53),IC(K,54),IC(K,55),",
    "     8IC(K,56),IC(K,57),IC(K,58),IC(K,59),IC(K,60),IC(K,61),IC(K,62),",
    "     9IC(K,63),IC(K,64),IC(K,65),IC(K,66),IC(K,67),IC(K,68),IC(K,69),",
    "     AIC(K,70),IC(K,71),IC(K,72)",
    "      WRITE (6,57) B(1),B(2),B(3),B(4),B(5),B(6),B(7),B(8),B(9),B(10),",
    "     1B(11),B(12),B(13),B(14),B(15),B(16),B(17),B(18),B(19),B(20),",
    "     2B(21),B(22),B(23),B(24),B(25),B(26),B(27),B(28),B(29),B(30),",
    "     3B(31),B(32),B(33),B(34),B(35),B(36),B(37),B(38),B(39),B(40),",
    "     4B(41),B(42),B(43),B(44),B(45),B(46),B(47),B(48),B(49),B(50),",
    "     5B(51),B(52),B(53),B(54),B(55),B(56),B(57),B(58),B(59),B(60),",
    "     6B(61),B(62),B(63),B(64),B(65),B(66),B(67),B(68),B(69),B(70),",
    "     7B(71),B(72)",
    "   56 FORMAT (1X,72I1)",
    "   57 FORMAT (1X,72F1.0)",
    "   70 CONTINUE",
    "      SEC = FLOAT(LEN)/8.0",
    "      WRITE (6,75) NB, SEC",
    "   75 FORMAT (1H0,I4,",
    "     1' BOWS PUNCHED AS TAPE CARDS. AT 120 BEATS A MINUTE THE',",
    "     2' TAPE LASTS',F7.1,' SECONDS.')",
    "      STOP",
    "      END",
    " 1960 1008    4",
    "   59",
    "   66",
    "   59",
    "   66"
  ] },
  { id: "poeme-symphonique", name: "Poème symphonique (ten metronomes, after Ligeti)", cards: [
    "C     POEME SYMPHONIQUE, AFTER GYORGY LIGETI (1962)",
    "C     LIGETI'S PIECE IS FOR 100 METRONOMES, WOUND UP, SET TO DIFFERENT",
    "C     SPEEDS AND STARTED TOGETHER; IT ENDS WHEN THE LAST ONE STOPS.",
    "C     HERE ONE PERFORMER TENDS UP TO TWENTY. EACH METRONOME GETS A",
    "C     SPEED BY CHANCE (A TICK EVERY 2 TO 8 PULSES), A WINDING GOOD FOR",
    "C     20 TO 35 TICKS, SO THE FAST ONES RUN DOWN FIRST, AND A START UP",
    "C     TO 3 PULSES LATE, SINCE NO ONE CAN START THEM ALL AT ONCE. EACH",
    "C     METRONOME TICKS ON ITS OWN HIGH NOTE. EVERY TICK IS PUNCHED AS A",
    "C     TAPE CARD (4I5): TIME IN PULSES, NOTE (MIDI NUMBER), LENGTH 1,",
    "C     LOUDNESS 1 TO 9. AT 120 BEATS A MINUTE A PULSE IS 1/8 SECOND.",
    "C     DATA CARD (2I5): SEED (1 TO 30268), METRONOMES (1 TO 20)",
    "C     THE CHART: ONE ROW PER METRONOME, AN ASTERISK WHILE IT TICKS AND",
    "C     A FULL STOP ONCE IT HAS STOPPED.",
    "      DIMENSION IP(20), NT(20), IS(20), IE(20), R(72)",
    "      READ (5,10) IX, M",
    "   10 FORMAT (2I5)",
    "      WRITE (6,15) M",
    "   15 FORMAT (1H1,'POEME SYMPHONIQUE FOR',I3,' METRONOMES'/1H0,",
    "     1' METRONOME  TICKS A MINUTE  TICKS  STARTS  STOPS')",
    "      LAST = 0",
    "      NTOT = 0",
    "      DO 30 K = 1, M",
    "      IX = MOD(171*IX, 30269)",
    "      IP(K) = 2 + MOD(IX, 7)",
    "      IX = MOD(171*IX, 30269)",
    "      NT(K) = 20 + MOD(IX, 16)",
    "      IX = MOD(171*IX, 30269)",
    "      IS(K) = MOD(IX, 4)",
    "      IE(K) = IS(K) + (NT(K) - 1)*IP(K)",
    "      LAST = MAX0(LAST, IE(K))",
    "      NTOT = NTOT + NT(K)",
    "      NOTE = 84 + K",
    "      N = NT(K)",
    "      DO 20 J = 1, N",
    "      IT = IS(K) + (J - 1)*IP(K)",
    "      LOUD = 5",
    "      IF (J .EQ. 1) LOUD = 7",
    "      PUNCH 18, IT, NOTE, 1, LOUD",
    "   18 FORMAT (4I5)",
    "   20 CONTINUE",
    "      IPM = 480/IP(K)",
    "      WRITE (6,25) K, IPM, NT(K), IS(K), IE(K)",
    "   25 FORMAT (1X,I10,I16,I7,I8,I7)",
    "   30 CONTINUE",
    "      IW = LAST/72 + 1",
    "      WRITE (6,35) IW",
    "   35 FORMAT (1H0,'THE METRONOMES RUNNING,',I3,' PULSES TO A COLUMN')",
    "      DO 50 K = 1, M",
    "      DO 45 L = 1, 72",
    "      R(L) = 0.0",
    "      IF ((L-1)*IW .LE. IE(K)) R(L) = 1.0",
    "   45 CONTINUE",
    "      WRITE (6,46) K, R(1),R(2),R(3),R(4),R(5),R(6),R(7),R(8),R(9),",
    "     1R(10),R(11),R(12),R(13),R(14),R(15),R(16),R(17),R(18),R(19),",
    "     2R(20),R(21),R(22),R(23),R(24),R(25),R(26),R(27),R(28),R(29),",
    "     3R(30),R(31),R(32),R(33),R(34),R(35),R(36),R(37),R(38),R(39),",
    "     4R(40),R(41),R(42),R(43),R(44),R(45),R(46),R(47),R(48),R(49),",
    "     5R(50),R(51),R(52),R(53),R(54),R(55),R(56),R(57),R(58),R(59),",
    "     6R(60),R(61),R(62),R(63),R(64),R(65),R(66),R(67),R(68),R(69),",
    "     7R(70),R(71),R(72)",
    "   46 FORMAT (1X,I3,2X,72F1.0)",
    "   50 CONTINUE",
    "      SEC = FLOAT(LAST)/8.0",
    "      WRITE (6,55) LAST, SEC, NTOT",
    "   55 FORMAT (1H0,'THE LAST METRONOME STOPS AT PULSE',I5,', AFTER',F6.1,",
    "     1' SECONDS'/1X,'AT 120 BEATS A MINUTE.',I5,",
    "     2' TICKS PUNCHED AS TAPE CARDS.')",
    "      STOP",
    "      END",
    " 1962   10"
  ] },
  { id: "sound-chess", name: "Sound chess (a listening game, after Takako Saito)", cards: [
    "C     SOUND CHESS: A LISTENING GAME, AFTER TAKAKO SAITO",
    "C     SAITO MADE CHESS SETS FOR FLUXUS IN WHICH EVERY PIECE IS THE SAME",
    "C     PLAIN BOX AND ONLY ITS SOUND SAYS WHAT IT IS. HERE THE 32 BOXES",
    "C     ARE MIXED BY CHANCE AND SHAKEN ONE BY ONE ON TAPE. A PAWN HOLDS",
    "C     ONE GRAIN, A KNIGHT 2, A BISHOP 3, A ROOK 4, THE QUEEN 5 AND THE",
    "C     KING 6; WHITE BOXES RATTLE HIGH AND BLACK ONES LOW. PLAY THE",
    "C     STACKER ON THE TAPE PLAYER, COUNT THE GRAINS IN EACH SHAKE, WRITE",
    "C     DOWN THE PIECES, THEN TURN TO THE ANSWERS ON THE SECOND PAGE.",
    "C     EACH GRAIN IS PUNCHED AS A TAPE CARD (4I5): TIME IN PULSES, NOTE",
    "C     (MIDI NUMBER), LENGTH 1, LOUDNESS 1 TO 9. A BOX IS SHAKEN FOR 16",
    "C     PULSES, TWO SECONDS AT 120 BEATS A MINUTE, ITS GRAINS FALLING ON",
    "C     DIFFERENT EVEN PULSES SO THAT THEY CAN BE COUNTED.",
    "C     DATA CARD (3I5): SEED (1 TO 30268), BOXES TO SHAKE (1 TO 32),",
    "C        PULSES FROM ONE BOX TO THE NEXT (AT LEAST 18)",
    "      DIMENSION KT(32), KC(32), IP(32), IQ(8)",
    "      READ (5,10) IX, NB, IG",
    "   10 FORMAT (3I5)",
    "C     THE SET: 8 PAWNS, 2 KNIGHTS, 2 BISHOPS, 2 ROOKS, A QUEEN AND A",
    "C     KING OF EACH COLOUR. KT IS THE KIND (1 PAWN TO 6 KING), KC THE",
    "C     COLOUR (1 WHITE, 2 BLACK)",
    "      DO 15 L = 1, 2",
    "      DO 12 J = 1, 16",
    "      K = (L - 1)*16 + J",
    "      KC(K) = L",
    "      KT(K) = 1",
    "      IF (J .GT. 8) KT(K) = 2 + (J - 9)/2",
    "      IF (J .EQ. 15) KT(K) = 5",
    "      IF (J .EQ. 16) KT(K) = 6",
    "   12 IP(K) = K",
    "   15 CONTINUE",
    "C     MIX THE BOXES",
    "      DO 20 L = 1, 31",
    "      K = 33 - L",
    "      IX = MOD(171*IX, 30269)",
    "      J = MOD(IX, K) + 1",
    "      IT = IP(K)",
    "      IP(K) = IP(J)",
    "   20 IP(J) = IT",
    "      WRITE (6,25)",
    "   25 FORMAT (1H1,'SOUND CHESS, A LISTENING GAME'/1H0,",
    "     1'A PAWN HOLDS ONE GRAIN,',",
    "     2' A KNIGHT 2, A BISHOP 3, A ROOK 4, THE QUEEN 5, THE KING 6.'/1X,",
    "     3'WHITE BOXES RATTLE HIGH, BLACK ONES LOW.'/1H0,",
    "     4'  BOX  SHAKEN AT PULSE   WHAT DID YOU HEAR?')",
    "C     SHAKE EACH BOX: ITS GRAINS FALL ON DIFFERENT SLOTS OF THE 8",
    "      NG = 0",
    "      DO 50 IBX = 1, NB",
    "      K = IP(IBX)",
    "      IT0 = (IBX - 1)*IG",
    "      WRITE (6,30) IBX, IT0",
    "   30 FORMAT (1H0,I5,I17,'   ____________________')",
    "      NOTE = 84",
    "      IF (KC(K) .EQ. 2) NOTE = 67",
    "      DO 35 J = 1, 8",
    "   35 IQ(J) = J - 1",
    "      N = KT(K)",
    "      DO 45 J = 1, N",
    "      JJ = 9 - J",
    "      IX = MOD(171*IX, 30269)",
    "      L = MOD(IX, JJ) + 1",
    "      IT = IQ(L)",
    "      IQ(L) = IQ(JJ)",
    "      IQ(JJ) = IT",
    "      IT = IT0 + 2*IT",
    "      IX = MOD(171*IX, 30269)",
    "      LOUD = 5 + MOD(IX, 3)",
    "      PUNCH 40, IT, NOTE, 1, LOUD",
    "   40 FORMAT (4I5)",
    "      NG = NG + 1",
    "   45 CONTINUE",
    "   50 CONTINUE",
    "C     THE ANSWERS, ON A NEW PAGE",
    "      WRITE (6,55)",
    "   55 FORMAT (1H1,'SOUND CHESS: THE ANSWERS'/1H0,'  BOX  PIECE')",
    "      DO 70 IBX = 1, NB",
    "      K = IP(IBX)",
    "      I = KT(K) + 6*(KC(K) - 1)",
    "      IF (I .EQ. 1) WRITE (6,101) IBX",
    "      IF (I .EQ. 2) WRITE (6,102) IBX",
    "      IF (I .EQ. 3) WRITE (6,103) IBX",
    "      IF (I .EQ. 4) WRITE (6,104) IBX",
    "      IF (I .EQ. 5) WRITE (6,105) IBX",
    "      IF (I .EQ. 6) WRITE (6,106) IBX",
    "      IF (I .EQ. 7) WRITE (6,107) IBX",
    "      IF (I .EQ. 8) WRITE (6,108) IBX",
    "      IF (I .EQ. 9) WRITE (6,109) IBX",
    "      IF (I .EQ. 10) WRITE (6,110) IBX",
    "      IF (I .EQ. 11) WRITE (6,111) IBX",
    "      IF (I .EQ. 12) WRITE (6,112) IBX",
    "   70 CONTINUE",
    "      WRITE (6,75) NG",
    "   75 FORMAT (1H0,I4,' GRAINS PUNCHED AS TAPE CARDS.')",
    "      STOP",
    "  101 FORMAT (1X,I5,2X,'WHITE PAWN')",
    "  102 FORMAT (1X,I5,2X,'WHITE KNIGHT')",
    "  103 FORMAT (1X,I5,2X,'WHITE BISHOP')",
    "  104 FORMAT (1X,I5,2X,'WHITE ROOK')",
    "  105 FORMAT (1X,I5,2X,'WHITE QUEEN')",
    "  106 FORMAT (1X,I5,2X,'WHITE KING')",
    "  107 FORMAT (1X,I5,2X,'BLACK PAWN')",
    "  108 FORMAT (1X,I5,2X,'BLACK KNIGHT')",
    "  109 FORMAT (1X,I5,2X,'BLACK BISHOP')",
    "  110 FORMAT (1X,I5,2X,'BLACK ROOK')",
    "  111 FORMAT (1X,I5,2X,'BLACK QUEEN')",
    "  112 FORMAT (1X,I5,2X,'BLACK KING')",
    "      END",
    " 1965   12   24"
  ] }
]
