[
  { id: "car-and-cdr", name: "Car and cdr (after McCarthy)", cards: [
    "C     CAR AND CDR: LIST CELLS IN TWO ARRAYS, AFTER JOHN MCCARTHY (1960)",
    "C     ON THE IBM 704 A LIST CELL WAS ONE WORD. ITS ADDRESS PART HELD THE",
    "C     CAR, THE FIRST ELEMENT, AND ITS DECREMENT PART THE CDR, THE REST",
    "C     OF THE LIST. HERE THE TWO PARTS ARE TWO ARRAYS, ICAR AND ICDR, OF",
    "C     40 CELLS, AND A CDR OF 0 IS NIL, THE END OF A LIST. THE UNUSED",
    "C     CELLS ARE CHAINED ON THE FREE-STORAGE LIST, AND CONS TAKES THE",
    "C     FIRST OF THEM. THE DECK BUILDS A LIST L FROM THE ATOMS ON ITS DATA",
    "C     CARD, REVERSES IT, AND APPENDS THE REVERSED LIST TO L. IT PRINTS",
    "C     EVERY CONS AS IT HAPPENS, THEN THE THREE LISTS, AND CHECKS WHICH",
    "C     CELLS THE LAST TWO SHARE.",
    "C     CONS IS WRITTEN ONCE, AT LABEL 900, AND GOES BACK TO ITS CALLER BY",
    "C     A COMPUTED GO TO. APPEND, WHICH LISP WRITES AS A RECURSION, KEEPS",
    "C     ITS PLACE ON A PUSH-DOWN LIST, THE ARRAY ISTK.",
    "C     THE PRINTER CANNOT PUT A PARENTHESIS WHERE IT WAS NOT TOLD TO, SO",
    "C     THERE IS ONE FORMAT FOR EACH LENGTH OF LIST, FROM 1 TO 10.",
    "C     DATA CARD (6I5): HOW MANY ATOMS (1 TO 5), THEN THE ATOMS (0 TO 9)",
    "C     TRY 1 ATOM, OR 5 DIGITS OF YOUR TELEPHONE NUMBER.",
    "      DIMENSION ICAR(40), ICDR(40), IA(5), IV(10), ISTK(10)",
    "      READ (5,10) N, IA(1), IA(2), IA(3), IA(4), IA(5)",
    "   10 FORMAT (6I5)",
    "      IF (N .LT. 1) N = 1",
    "      IF (N .GT. 5) N = 5",
    "      WRITE (6,12)",
    "   12 FORMAT (1H1,'CAR AND CDR'/1H0,'CONS   CAR   CDR   TAKES CELL',",
    "     1 '   FREE LIST NOW BEGINS AT')",
    "C     CHAIN EVERY CELL ON THE FREE-STORAGE LIST",
    "      DO 14 K = 1, 40",
    "      ICAR(K) = 0",
    "      ICDR(K) = K + 1",
    "   14 CONTINUE",
    "      ICDR(40) = 0",
    "      IFREE = 1",
    "      NC = 0",
    "C     BUILD L FROM ITS LAST ATOM BACK TO ITS FIRST: L = CONS(ATOM, L)",
    "      WRITE (6,15)",
    "   15 FORMAT (1H ,'BUILD L')",
    "      L = 0",
    "      I = N",
    "   20 IX = IA(I)",
    "      IY = L",
    "      IRET = 1",
    "      GO TO 900",
    "   21 L = K",
    "      I = I - 1",
    "      IF (I .GE. 1) GO TO 20",
    "C     REVERSE L: CONS EACH CAR OF L IN TURN ONTO R, WHICH BEGINS AS NIL",
    "      WRITE (6,25)",
    "   25 FORMAT (1H ,'REVERSE L')",
    "      IR = 0",
    "      IP = L",
    "   30 IX = ICAR(IP)",
    "      IY = IR",
    "      IRET = 2",
    "      GO TO 900",
    "   31 IR = K",
    "      IP = ICDR(IP)",
    "      IF (IP .NE. 0) GO TO 30",
    "C     APPEND L R: PUSH THE CARS OF L ON THE PUSH-DOWN LIST, THEN POP",
    "C     THEM ONE BY ONE, CONSING EACH ONTO WHAT IS BUILT, BEGINNING AT R",
    "      WRITE (6,35)",
    "   35 FORMAT (1H ,'APPEND L R')",
    "      NS = 0",
    "      IP = L",
    "   40 NS = NS + 1",
    "      ISTK(NS) = ICAR(IP)",
    "      IP = ICDR(IP)",
    "      IF (IP .NE. 0) GO TO 40",
    "      IAP = IR",
    "   42 IX = ISTK(NS)",
    "      IY = IAP",
    "      IRET = 3",
    "      GO TO 900",
    "   43 IAP = K",
    "      NS = NS - 1",
    "      IF (NS .GT. 0) GO TO 42",
    "C     PRINT THE THREE LISTS",
    "      WRITE (6,50)",
    "   50 FORMAT (1H0,'THE LISTS, READ BY FOLLOWING EACH CDR TO NIL'/1H )",
    "      WRITE (6,51) L",
    "   51 FORMAT (1X,'L',14X,'CELL',I3)",
    "      IP = L",
    "      JRET = 1",
    "      GO TO 800",
    "   52 WRITE (6,53) IR",
    "   53 FORMAT (1X,'R = REVERSE L',2X,'CELL',I3)",
    "      IP = IR",
    "      JRET = 2",
    "      GO TO 800",
    "   54 WRITE (6,55) IAP",
    "   55 FORMAT (1X,'APPEND L R',5X,'CELL',I3)",
    "      IP = IAP",
    "      JRET = 3",
    "      GO TO 800",
    "C     FOLLOW THE APPENDED LIST N CELLS: IT SHOULD THEN BE AT R ITSELF",
    "   56 IP = IAP",
    "      DO 57 I = 1, N",
    "      IP = ICDR(IP)",
    "   57 CONTINUE",
    "      IF (IP .EQ. IR) WRITE (6,58) IR, N, N",
    "   58 FORMAT (1H0,'THE APPENDED LIST RUNS ON INTO CELL',I3,",
    "     1 ', THE FIRST CELL OF R.'/1H ,'NEW CELLS, A COPY OF L:',I3/",
    "     2 1H ,'CELLS SHARED WITH R:',I6)",
    "C     COUNT WHAT IS LEFT ON THE FREE-STORAGE LIST",
    "      NF = 0",
    "      IP = IFREE",
    "   64 IF (IP .EQ. 0) GO TO 66",
    "      NF = NF + 1",
    "      IP = ICDR(IP)",
    "      GO TO 64",
    "   66 WRITE (6,67) NC, NF, IFREE",
    "   67 FORMAT (1H0,I3,' CELLS IN USE,',I3,' ON THE FREE-STORAGE LIST,',",
    "     1 ' WHICH BEGINS AT CELL',I3)",
    "      STOP",
    "C     PRINT THE LIST THAT BEGINS AT CELL IP, OVER THE LINE JUST PRINTED",
    "  800 NV = 0",
    "  801 NV = NV + 1",
    "      IV(NV) = ICAR(IP)",
    "      IP = ICDR(IP)",
    "      IF (IP .NE. 0 .AND. NV .LT. 10) GO TO 801",
    "      GO TO (811,812,813,814,815,816,817,818,819,820), NV",
    "  811 WRITE (6,821) IV(1)",
    "      GO TO 840",
    "  812 WRITE (6,822) IV(1),IV(2)",
    "      GO TO 840",
    "  813 WRITE (6,823) IV(1),IV(2),IV(3)",
    "      GO TO 840",
    "  814 WRITE (6,824) IV(1),IV(2),IV(3),IV(4)",
    "      GO TO 840",
    "  815 WRITE (6,825) IV(1),IV(2),IV(3),IV(4),IV(5)",
    "      GO TO 840",
    "  816 WRITE (6,826) IV(1),IV(2),IV(3),IV(4),IV(5),IV(6)",
    "      GO TO 840",
    "  817 WRITE (6,827) IV(1),IV(2),IV(3),IV(4),IV(5),IV(6),IV(7)",
    "      GO TO 840",
    "  818 WRITE (6,828) IV(1),IV(2),IV(3),IV(4),IV(5),IV(6),IV(7),IV(8)",
    "      GO TO 840",
    "  819 WRITE (6,829) IV(1),IV(2),IV(3),IV(4),IV(5),IV(6),IV(7),IV(8),",
    "     1 IV(9)",
    "      GO TO 840",
    "  820 WRITE (6,830) IV(1),IV(2),IV(3),IV(4),IV(5),IV(6),IV(7),IV(8),",
    "     1 IV(9),IV(10)",
    "  840 GO TO (52,54,56), JRET",
    "  821 FORMAT (1H+,24X,'(',I1,')')",
    "  822 FORMAT (1H+,24X,'(',I1,1(1X,I1),')')",
    "  823 FORMAT (1H+,24X,'(',I1,2(1X,I1),')')",
    "  824 FORMAT (1H+,24X,'(',I1,3(1X,I1),')')",
    "  825 FORMAT (1H+,24X,'(',I1,4(1X,I1),')')",
    "  826 FORMAT (1H+,24X,'(',I1,5(1X,I1),')')",
    "  827 FORMAT (1H+,24X,'(',I1,6(1X,I1),')')",
    "  828 FORMAT (1H+,24X,'(',I1,7(1X,I1),')')",
    "  829 FORMAT (1H+,24X,'(',I1,8(1X,I1),')')",
    "  830 FORMAT (1H+,24X,'(',I1,9(1X,I1),')')",
    "C     CONS: TAKE THE FIRST FREE CELL, PUT IX IN ITS CAR AND IY IN ITS",
    "C     CDR, AND RETURN THE CELL IN K",
    "  900 K = IFREE",
    "      IFREE = ICDR(K)",
    "      ICAR(K) = IX",
    "      ICDR(K) = IY",
    "      NC = NC + 1",
    "      WRITE (6,905) NC, IX, IY, K, IFREE",
    "  905 FORMAT (1X,I4,I6,I6,I13,I26)",
    "      GO TO (21,31,43), IRET",
    "      END",
    "    5    3    1    4    1    5"
  ] },
  { id: "tower-of-hanoi", name: "The tower of Hanoi (recursion without recursion)", cards: [
    "C     THE TOWER OF HANOI, BY RECURSION WITHOUT RECURSION",
    "C     TO MOVE N DISCS FROM ONE PEG TO ANOTHER: MOVE N-1 DISCS OUT OF THE",
    "C     WAY, ONTO THE THIRD PEG; MOVE THE LARGEST DISC; THEN MOVE THE N-1",
    "C     DISCS BACK ON TOP OF IT. IN LISP THAT IS A RECURSIVE FUNCTION OF",
    "C     THREE LINES. THIS FORTRAN CANNOT CALL ITSELF, SO EACH CALL NOT YET",
    "C     FINISHED IS A FRAME ON A PUSH-DOWN LIST: HOW MANY DISCS (KN), FROM",
    "C     WHICH PEG (KF), TO WHICH (KT), AND HOW FAR IT HAS GOT (KS). A",
    "C     FRAME IS PUSHED FOR EACH CALL AND POPPED WHEN THE CALL IS DONE.",
    "C     EACH MOVE IS PRINTED WITH THE PUSH-DOWN LIST AS IT STANDS, ONE",
    "C     ASTERISK FOR EACH FRAME, AND THE PEGS AFTER THE MOVE, THE DISCS ON",
    "C     EACH READ FROM THE BOTTOM UP (A FULL STOP IS AN EMPTY PEG).",
    "C     DATA CARD (I5): HOW MANY DISCS (1 TO 7)",
    "C     TRY 3 DISCS FOR 7 MOVES, OR 7 FOR 127.",
    "      DIMENSION KN(9), KF(9), KT(9), KS(9), G(9), IPEG(3), NPEG(3)",
    "      READ (5,10) N",
    "   10 FORMAT (I5)",
    "      IF (N .LT. 1) N = 1",
    "      IF (N .GT. 7) N = 7",
    "      WRITE (6,12) N",
    "   12 FORMAT (1H1,'THE TOWER OF HANOI,',I2,' DISCS FROM PEG A TO PEG C'/",
    "     1 1H0,'MOVE',4X,'DISC',4X,'FROM   TO',5X,'PUSH-DOWN LIST',8X,",
    "     2 'A',8X,'B',8X,'C')",
    "C     THE PEGS AS NUMBERS: PEG A HOLDS N ... 3 2 1, READ AS DIGITS",
    "      IPEG(1) = 0",
    "      DO 14 I = 1, N",
    "      IPEG(1) = 10*IPEG(1) + (N + 1 - I)",
    "   14 CONTINUE",
    "      IPEG(2) = 0",
    "      IPEG(3) = 0",
    "      NPEG(1) = N",
    "      NPEG(2) = 0",
    "      NPEG(3) = 0",
    "      WRITE (6,16) IPEG(1)",
    "   16 FORMAT (1X,'   0',42X,I7,8X,'.',8X,'.')",
    "      NM = 0",
    "      NPUSH = 1",
    "      MAXD = 1",
    "C     THE FIRST CALL: N DISCS FROM PEG 1 TO PEG 3",
    "      ND = 1",
    "      KN(1) = N",
    "      KF(1) = 1",
    "      KT(1) = 3",
    "      KS(1) = 0",
    "   20 IF (ND .EQ. 0) GO TO 90",
    "      IF (KN(ND) .EQ. 0) GO TO 40",
    "      IF (KS(ND) .EQ. 1) GO TO 30",
    "      IF (KS(ND) .EQ. 2) GO TO 40",
    "C     STAGE 0: PUSH A CALL TO MOVE N-1 DISCS ONTO THE SPARE PEG",
    "      KS(ND) = 1",
    "      IP = ND",
    "      ND = ND + 1",
    "      KN(ND) = KN(IP) - 1",
    "      KF(ND) = KF(IP)",
    "      KT(ND) = 6 - KF(IP) - KT(IP)",
    "      KS(ND) = 0",
    "      GO TO 50",
    "C     STAGE 1: MOVE THE LARGEST DISC, THEN PUSH A CALL TO MOVE THE N-1",
    "C     DISCS FROM THE SPARE PEG ON TOP OF IT",
    "   30 KS(ND) = 2",
    "      IFR = KF(ND)",
    "      ITO = KT(ND)",
    "      ID = MOD(IPEG(IFR), 10)",
    "      IPEG(IFR) = IPEG(IFR)/10",
    "      IPEG(ITO) = 10*IPEG(ITO) + ID",
    "      NPEG(IFR) = NPEG(IFR) - 1",
    "      NPEG(ITO) = NPEG(ITO) + 1",
    "      NM = NM + 1",
    "      DO 32 I = 1, 9",
    "      G(I) = 0.0",
    "      IF (I .LE. ND) G(I) = 1.0",
    "   32 CONTINUE",
    "      JF = 3*(IFR - 1) + ITO",
    "      WRITE (6,34) NM, ID, G(1),G(2),G(3),G(4),G(5),G(6),G(7),G(8),",
    "     1 G(9)",
    "   34 FORMAT (1X,I4,I8,24X,9F1.0)",
    "      GO TO (60,61,62,63,60,64,65,66,60), JF",
    "   60 GO TO 36",
    "   61 WRITE (6,71)",
    "      GO TO 36",
    "   62 WRITE (6,72)",
    "      GO TO 36",
    "   63 WRITE (6,73)",
    "      GO TO 36",
    "   64 WRITE (6,74)",
    "      GO TO 36",
    "   65 WRITE (6,75)",
    "      GO TO 36",
    "   66 WRITE (6,76)",
    "C     THE PEGS, OVER THE SAME LINE: AN EMPTY PEG IS A FULL STOP",
    "   36 DO 38 J = 1, 3",
    "      IF (NPEG(J) .EQ. 0) GO TO 38",
    "      GO TO (81,82,83), J",
    "   81 WRITE (6,84) IPEG(1)",
    "      GO TO 38",
    "   82 WRITE (6,85) IPEG(2)",
    "      GO TO 38",
    "   83 WRITE (6,86) IPEG(3)",
    "   38 CONTINUE",
    "      DO 39 J = 1, 3",
    "      IF (NPEG(J) .NE. 0) GO TO 39",
    "      GO TO (87,88,89), J",
    "   87 WRITE (6,77)",
    "      GO TO 39",
    "   88 WRITE (6,78)",
    "      GO TO 39",
    "   89 WRITE (6,79)",
    "   39 CONTINUE",
    "      IP = ND",
    "      ND = ND + 1",
    "      KN(ND) = KN(IP) - 1",
    "      KF(ND) = 6 - KF(IP) - KT(IP)",
    "      KT(ND) = KT(IP)",
    "      KS(ND) = 0",
    "      GO TO 50",
    "C     A CALL WITH NO DISCS, OR ONE THAT HAS FINISHED: POP ITS FRAME",
    "   40 ND = ND - 1",
    "      GO TO 20",
    "C     COUNT EVERY PUSH, AND THE DEEPEST THE PUSH-DOWN LIST HAS BEEN",
    "   50 NPUSH = NPUSH + 1",
    "      IF (ND .GT. MAXD) MAXD = ND",
    "      GO TO 20",
    "   90 MIN = 2**N - 1",
    "      WRITE (6,92) NM, MIN, NPUSH, MAXD",
    "   92 FORMAT (1H0,'MOVES MADE',I20/1H ,'FEWEST POSSIBLE, 2**N - 1',I5/",
    "     1 1H ,'FRAMES PUSHED',I17/1H ,'DEEPEST PUSH-DOWN LIST',I8)",
    "      STOP",
    "   71 FORMAT (1H+,18X,'A',5X,'B')",
    "   72 FORMAT (1H+,18X,'A',5X,'C')",
    "   73 FORMAT (1H+,18X,'B',5X,'A')",
    "   74 FORMAT (1H+,18X,'B',5X,'C')",
    "   75 FORMAT (1H+,18X,'C',5X,'A')",
    "   76 FORMAT (1H+,18X,'C',5X,'B')",
    "   77 FORMAT (1H+,52X,'.')",
    "   78 FORMAT (1H+,61X,'.')",
    "   79 FORMAT (1H+,70X,'.')",
    "   84 FORMAT (1H+,46X,I7)",
    "   85 FORMAT (1H+,55X,I7)",
    "   86 FORMAT (1H+,64X,I7)",
    "      END",
    "    4"
  ] },
  { id: "reclamation", name: "Reclamation (after McCarthy and Edwards)", cards: [
    "C     RECLAMATION: A MARK-AND-SWEEP GARBAGE COLLECTOR, AFTER MCCARTHY",
    "C     (1960) AND THE LISP 1.5 COLLECTOR OF DANIEL EDWARDS",
    "C     NOTHING IS EVER ERASED. A PROGRAM BUILDS LISTS AND PUTS EACH NEW",
    "C     LIST IN ONE OF FOUR BASE REGISTERS, ABANDONING THE LIST THAT WAS",
    "C     THERE. WHEN THE FREE-STORAGE LIST RUNS OUT, RECLAMATION BEGINS:",
    "C     EVERY CELL THAT CAN BE REACHED FROM A BASE REGISTER, OR FROM THE",
    "C     LIST HALF BUILT, BY A CHAIN OF CARS AND CDRS IS MARKED, AND EVERY",
    "C     CELL LEFT UNMARKED GOES BACK ON THE FREE-STORAGE LIST. THE CELLS",
    "C     STILL TO BE VISITED WAIT ON A PUSH-DOWN LIST, ISTK. THE 704 MARKED",
    "C     A CELL BY MAKING ITS SIGN NEGATIVE; HERE THE MARKS ARE AN ARRAY.",
    "C     STORAGE IS 60 CELLS. A CAR ABOVE 0 POINTS TO A CELL, A CAR BELOW 0",
    "C     IS AN ATOM, AND A CDR OF 0 IS NIL. AT EACH RECLAMATION THE PRINTER",
    "C     DRAWS STORAGE, CELL 1 AT THE LEFT: AN ASTERISK IS A CELL STILL IN",
    "C     USE, A FULL STOP ONE RECLAIMED.",
    "C     DATA CARD (3I5): SEED (1 TO 30268), LISTS TO BUILD (1 TO 99),",
    "C     CHANCE IN 10 THAT AN ELEMENT IS THE LIST IN ANOTHER BASE REGISTER",
    "C     (0 TO 5)",
    "C     TRY 0 FOR ATOMS ONLY, OR 5, AND WATCH SHARED LISTS FILL STORAGE.",
    "      DIMENSION ICAR(60), ICDR(60), MK(60), IB(4), ISTK(130), P(60)",
    "      READ (5,10) IX, NL, NSH",
    "   10 FORMAT (3I5)",
    "      WRITE (6,12)",
    "   12 FORMAT (1H1,'RECLAMATION'/1H0,'LIST  BASE  ATOMS  LISTS',",
    "     1 '  FIRST CELL')",
    "      DO 14 K = 1, 60",
    "      ICAR(K) = 0",
    "      ICDR(K) = K + 1",
    "   14 CONTINUE",
    "      ICDR(60) = 0",
    "      IFREE = 1",
    "      DO 15 J = 1, 4",
    "      IB(J) = 0",
    "   15 CONTINUE",
    "      NGC = 0",
    "      NCONS = 0",
    "      LL = 0",
    "C     A NEW LIST: CHOOSE ITS BASE REGISTER AND ITS LENGTH",
    "   20 LL = LL + 1",
    "      IF (LL .GT. NL) GO TO 90",
    "      IX = MOD(171*IX, 30269)",
    "      J = MOD(IX, 4) + 1",
    "      IX = MOD(171*IX, 30269)",
    "      M = MOD(IX, 5) + 1",
    "      NEW = 0",
    "      NAT = 0",
    "      NSUB = 0",
    "      I = 0",
    "C     AN ELEMENT: AN ATOM, OR NOW AND THEN THE LIST IN ANOTHER REGISTER",
    "   22 I = I + 1",
    "      IX = MOD(171*IX, 30269)",
    "      IA = -(MOD(IX, 9) + 1)",
    "      IX = MOD(171*IX, 30269)",
    "      JS = MOD(IX, 4) + 1",
    "      IX = MOD(171*IX, 30269)",
    "      IF (MOD(IX,10) .LT. NSH .AND. JS .NE. J) IA = IB(JS)",
    "      IF (IA .EQ. 0) IA = -(MOD(IX, 9) + 1)",
    "      IF (IA .LT. 0) NAT = NAT + 1",
    "      IF (IA .GT. 0) NSUB = NSUB + 1",
    "C     CONS THE ELEMENT ONTO THE LIST; IF NO CELL IS FREE, RECLAIM FIRST",
    "      IF (IFREE .EQ. 0) GO TO 60",
    "   24 K = IFREE",
    "      IFREE = ICDR(K)",
    "      ICAR(K) = IA",
    "      ICDR(K) = NEW",
    "      NEW = K",
    "      NCONS = NCONS + 1",
    "      IF (I .LT. M) GO TO 22",
    "C     THE FINISHED LIST GOES IN ITS REGISTER; THE OLD ONE IS ABANDONED",
    "      IB(J) = NEW",
    "      WRITE (6,26) LL, J, NAT, NSUB, NEW",
    "   26 FORMAT (1X,I4,I6,I7,I7,I12)",
    "      GO TO 20",
    "C     RECLAMATION. MARK: START FROM THE FOUR REGISTERS AND THE LIST HALF",
    "C     BUILT, AND FOLLOW EVERY CAR AND CDR FROM EVERY CELL REACHED",
    "   60 NGC = NGC + 1",
    "      DO 61 K = 1, 60",
    "      MK(K) = 0",
    "   61 CONTINUE",
    "      DO 62 JB = 1, 4",
    "      ISTK(JB) = IB(JB)",
    "   62 CONTINUE",
    "      ISTK(5) = NEW",
    "      NS = 5",
    "      MAXS = 5",
    "      NMK = 0",
    "   63 IF (NS .EQ. 0) GO TO 66",
    "      KP = ISTK(NS)",
    "      NS = NS - 1",
    "      IF (KP .LE. 0) GO TO 63",
    "      IF (MK(KP) .EQ. 1) GO TO 63",
    "      MK(KP) = 1",
    "      NMK = NMK + 1",
    "      ISTK(NS+1) = ICDR(KP)",
    "      ISTK(NS+2) = ICAR(KP)",
    "      NS = NS + 2",
    "      IF (NS .GT. MAXS) MAXS = NS",
    "      GO TO 63",
    "C     SWEEP: STRING EVERY UNMARKED CELL ON A NEW FREE-STORAGE LIST,",
    "C     FROM THE TOP DOWN, SO THAT THE LIST BEGINS AT THE LOWEST CELL",
    "   66 IFREE = 0",
    "      NFR = 0",
    "      DO 67 KK = 1, 60",
    "      K = 61 - KK",
    "      P(K) = FLOAT(MK(K))",
    "      IF (MK(K) .EQ. 1) GO TO 67",
    "      ICAR(K) = 0",
    "      ICDR(K) = IFREE",
    "      IFREE = K",
    "      NFR = NFR + 1",
    "   67 CONTINUE",
    "      WRITE (6,68) NGC, NCONS",
    "   68 FORMAT (1H0,'RECLAMATION',I3,', AFTER',I5,' CONSES'/",
    "     1 1H ,'CELL ',9X,'1',9X,'2',9X,'3',9X,'4',9X,'5',9X,'6'/",
    "     2 1H ,5X,6('1234567890'))",
    "      WRITE (6,69) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60)",
    "   69 FORMAT (1X,5X,60F1.0)",
    "      WRITE (6,70) NMK, MAXS, NFR",
    "   70 FORMAT (1H ,I7,' CELLS MARKED; THE PUSH-DOWN LIST WAS AT MOST',I4,",
    "     1 ' DEEP'/1H ,I7,' CELLS RETURNED TO FREE STORAGE'/1H )",
    "      IF (NFR .GT. 0) GO TO 24",
    "      WRITE (6,72)",
    "   72 FORMAT (1H ,'NOTHING COULD BE RECLAIMED. STORAGE IS FULL.')",
    "      STOP",
    "   90 WRITE (6,92) NL, NCONS, NGC",
    "   92 FORMAT (1H0,I5,' LISTS BUILT WITH',I5,' CONSES FROM 60 CELLS'/",
    "     1 1H ,I5,' RECLAMATIONS')",
    "      STOP",
    "      END",
    " 1960   80    2"
  ] },
  { id: "eval", name: "Eval (after McCarthy and Russell)", cards: [
    "C     EVAL: A SMALL LISP EVALUATOR, AFTER MCCARTHY (1960) AND RUSSELL",
    "C     IT READS S-EXPRESSIONS FROM ITS DATA CARDS, BUILDS EACH ONE AS",
    "C     LIST STRUCTURE IN TWO ARRAYS OF CELLS, ICAR AND ICDR, AND",
    "C     EVALUATES IT, PRINTING A TRACE OF EVERY FUNCTION AS IT BEGINS AND",
    "C     AS IT ENDS. IT",
    "C     KNOWS FOUR FUNCTIONS OF LISP 1.5: PLUS AND TIMES OF ANY NUMBER OF",
    "C     ARGUMENTS, DIFFERENCE AND QUOTIENT OF EXACTLY TWO. AN ARGUMENT MAY",
    "C     BE A NUMBER OR ANOTHER EXPRESSION, TO ANY DEPTH.",
    "C     THIS FORTRAN HAS NO RECURSION, SO BOTH THE READER AND EVAL KEEP",
    "C     THEIR PLACE ON PUSH-DOWN LISTS: THE READER THE LISTS IT HAS BEGUN,",
    "C     EVAL ONE FRAME FOR EACH FUNCTION NOT YET FINISHED. THE FIRST",
    "C     COLUMN OF THE TRACE SHOWS HOW DEEP EVAL'S PUSH-DOWN LIST IS, ONE",
    "C     ASTERISK FOR EACH FRAME.",
    "C     THE CARD READER OF THIS ROOM READS ONLY NUMBERS, SO EACH TOKEN OF",
    "C     AN EXPRESSION IS PUNCHED ON A CARD OF ITS OWN, AS A CODE.",
    "C     DATA CARDS (I1,I9), ONE PER TOKEN: IN COLUMN 1, 1 FOR (, 2 FOR ),",
    "C     3 FOR A NUMBER, 4 FOR A FUNCTION, 9 FOR STOP AFTER THE LAST",
    "C     EXPRESSION; IN COLUMNS 2 TO 10, THE NUMBER, OR THE FUNCTION: 1",
    "C     PLUS, 2 DIFFERENCE, 3 TIMES, 4 QUOTIENT. COLUMNS 21 TO 80 ARE FOR",
    "C     THE TOKEN AS WRITTEN, AND ARE NOT READ.",
    "C     TRY (DIFFERENCE 7) TO SEE AN ERROR, OR NEST TEN LISTS DEEP.",
    "      DIMENSION ICAR(200), ICDR(200), NUMB(100), IHS(20), ITS(20),",
    "     1 IFN(20), IPOS(20), NARG(20), IACC(20), G(8)",
    "      WRITE (6,10)",
    "   10 FORMAT (1H1,'EVAL')",
    "      NC = 0",
    "      NNUM = 0",
    "      NEXP = 0",
    "      ND = 0",
    "C     THE READER. A ( BEGINS A NEW LIST AND PUSHES THE ONE BEGUN BEFORE",
    "  100 READ (5,101) KIND, IVAL",
    "  101 FORMAT (I1,I9)",
    "      GO TO (110,120,130,140,102,102,102,102,190), KIND",
    "  102 WRITE (6,103) KIND",
    "  103 FORMAT (1H0,'CARD OF KIND',I2,' IS NOT A TOKEN')",
    "      STOP",
    "  110 IF (ND .EQ. 20) GO TO 430",
    "      ND = ND + 1",
    "      IHS(ND) = 0",
    "      ITS(ND) = 0",
    "      GO TO 100",
    "C     A ) ENDS THE LIST; IT BECOMES AN ELEMENT OF THE LIST POPPED",
    "  120 IF (ND .EQ. 0) GO TO 124",
    "      IA = IHS(ND)",
    "      ND = ND - 1",
    "      IF (ND .EQ. 0) GO TO 200",
    "      GO TO 150",
    "  124 WRITE (6,125)",
    "  125 FORMAT (1H0,'A ) WITH NO ( TO MATCH IT')",
    "      GO TO 100",
    "C     A NUMBER GOES IN FULL-WORD SPACE; ITS CAR IS -10 LESS ITS PLACE",
    "  130 NNUM = NNUM + 1",
    "      NUMB(NNUM) = IVAL",
    "      IA = -(10 + NNUM)",
    "      IF (ND .GT. 0) GO TO 150",
    "      NEXP = NEXP + 1",
    "      WRITE (6,132) NEXP, IVAL",
    "  132 FORMAT (1H0,'EXPRESSION',I3/1H0,'A NUMBER, WHICH IS ITS OWN',",
    "     1 ' VALUE:',I10)",
    "      GO TO 100",
    "C     A FUNCTION NAME IS AN ATOM WITH A CAR FROM -1 TO -4",
    "  140 IA = -IVAL",
    "      IF (IVAL .LT. 1 .OR. IVAL .GT. 4) IA = 0",
    "      IF (ND .GT. 0) GO TO 150",
    "      WRITE (6,142)",
    "  142 FORMAT (1H0,'A FUNCTION NAME OUTSIDE ANY LIST')",
    "      GO TO 100",
    "C     PUT ATOM OR LIST IA AT THE END OF THE LIST AT THE TOP OF THE STACK",
    "  150 NC = NC + 1",
    "      ICAR(NC) = IA",
    "      ICDR(NC) = 0",
    "      IF (ITS(ND) .EQ. 0) IHS(ND) = NC",
    "      IF (ITS(ND) .NE. 0) ICDR(ITS(ND)) = NC",
    "      ITS(ND) = NC",
    "      GO TO 100",
    "C     EVAL. EACH LIST IS A FUNCTION FOLLOWED BY ITS ARGUMENTS",
    "  200 NEXP = NEXP + 1",
    "      WRITE (6,202) NEXP",
    "  202 FORMAT (1H0,'EXPRESSION',I3/1H0,'PUSH-DOWN LIST     FUNCTION',",
    "     1 4X,'ARGUMENTS     VALUE')",
    "      IE = IA",
    "      NF = 0",
    "C     PUSH A FRAME FOR THE LIST IE",
    "  300 IF (IE .EQ. 0) GO TO 410",
    "      K = -ICAR(IE)",
    "      IF (K .LT. 1 .OR. K .GT. 4) GO TO 420",
    "      NF = NF + 1",
    "      IF (NF .GT. 20) GO TO 430",
    "      IFN(NF) = K",
    "      IPOS(NF) = ICDR(IE)",
    "      NARG(NF) = 0",
    "      IACC(NF) = 0",
    "      DO 302 I = 1, 8",
    "      G(I) = 0.0",
    "      IF (I .LE. NF) G(I) = 1.0",
    "  302 CONTINUE",
    "      WRITE (6,304) G(1),G(2),G(3),G(4),G(5),G(6),G(7),G(8)",
    "  304 FORMAT (1X,2X,8F1.0,21X,'BEGINS')",
    "      JRET = 1",
    "      GO TO 500",
    "C     TAKE THE NEXT ARGUMENT. A LIST IS EVALUATED FIRST, IN A NEW FRAME",
    "  310 IP = IPOS(NF)",
    "      IF (IP .EQ. 0) GO TO 350",
    "      IA = ICAR(IP)",
    "      IPOS(NF) = ICDR(IP)",
    "      IF (IA .GT. 0) GO TO 312",
    "      IF (IA .GE. -4) GO TO 440",
    "      IV = NUMB(-IA - 10)",
    "      GO TO 330",
    "  312 IE = IA",
    "      GO TO 300",
    "C     COMBINE THE VALUE IV WITH THE ARGUMENTS ALREADY TAKEN",
    "  330 NARG(NF) = NARG(NF) + 1",
    "      IF (NARG(NF) .GT. 1) GO TO 331",
    "      IACC(NF) = IV",
    "      GO TO 310",
    "  331 K = IFN(NF)",
    "      GO TO (332,333,334,335), K",
    "  332 IACC(NF) = IACC(NF) + IV",
    "      GO TO 310",
    "  333 IACC(NF) = IACC(NF) - IV",
    "      GO TO 310",
    "  334 IACC(NF) = IACC(NF)*IV",
    "      GO TO 310",
    "  335 IF (IV .EQ. 0) GO TO 450",
    "      IACC(NF) = IACC(NF)/IV",
    "      GO TO 310",
    "C     NO ARGUMENTS LEFT: THE FUNCTION ENDS, AND ITS FRAME IS POPPED",
    "  350 K = IFN(NF)",
    "      N = NARG(NF)",
    "      IF ((K .EQ. 2 .OR. K .EQ. 4) .AND. N .NE. 2) GO TO 460",
    "      IF (K .EQ. 3 .AND. N .EQ. 0) IACC(NF) = 1",
    "      IV = IACC(NF)",
    "      DO 352 I = 1, 8",
    "      G(I) = 0.0",
    "      IF (I .LE. NF) G(I) = 1.0",
    "  352 CONTINUE",
    "      WRITE (6,354) G(1),G(2),G(3),G(4),G(5),G(6),G(7),G(8), N, IV",
    "  354 FORMAT (1X,2X,8F1.0,20X,I6,I14)",
    "      JRET = 2",
    "      GO TO 500",
    "  356 NF = NF - 1",
    "      IF (NF .GT. 0) GO TO 330",
    "      WRITE (6,358) IV",
    "  358 FORMAT (1H0,'VALUE',I10)",
    "      GO TO 100",
    "C     ERRORS. THE REST OF THE EXPRESSION IS ABANDONED",
    "  410 WRITE (6,411)",
    "  411 FORMAT (1H0,'ERROR: AN EMPTY LIST, NIL, HAS NO FUNCTION')",
    "      GO TO 100",
    "  420 WRITE (6,421)",
    "  421 FORMAT (1H0,'ERROR: A LIST MUST BEGIN WITH A FUNCTION')",
    "      GO TO 100",
    "  430 WRITE (6,431)",
    "  431 FORMAT (1H0,'ERROR: THE PUSH-DOWN LIST IS FULL')",
    "      STOP",
    "  440 WRITE (6,441)",
    "  441 FORMAT (1H0,'ERROR: AN ARGUMENT MUST BE A NUMBER OR A LIST')",
    "      GO TO 100",
    "  450 WRITE (6,451)",
    "  451 FORMAT (1H0,'ERROR: DIVIDE CHECK, A QUOTIENT BY 0')",
    "      GO TO 100",
    "  460 WRITE (6,461) N",
    "  461 FORMAT (1H0,'ERROR: THIS FUNCTION NEEDS 2 ARGUMENTS, NOT',I3)",
    "      GO TO 100",
    "C     THE STOP CARD",
    "  190 WRITE (6,191) NEXP, NC, NNUM",
    "  191 FORMAT (1H0,I3,' EXPRESSIONS,',I4,' LIST CELLS,',I4,' NUMBERS',",
    "     1 ' IN FULL-WORD SPACE')",
    "      STOP",
    "C     PRINT THE NAME OF FUNCTION IFN(NF) OVER THE LINE JUST PRINTED",
    "  500 K = IFN(NF)",
    "      GO TO (501,502,503,504), K",
    "  501 WRITE (6,511)",
    "      GO TO 520",
    "  502 WRITE (6,512)",
    "      GO TO 520",
    "  503 WRITE (6,513)",
    "      GO TO 520",
    "  504 WRITE (6,514)",
    "  520 GO TO (310,356), JRET",
    "  511 FORMAT (1H+,19X,'PLUS')",
    "  512 FORMAT (1H+,19X,'DIFFERENCE')",
    "  513 FORMAT (1H+,19X,'TIMES')",
    "  514 FORMAT (1H+,19X,'QUOTIENT')",
    "      END",
    "1                   (",
    "4        1            PLUS",
    "3        1            1",
    "1                     (",
    "4        3              TIMES",
    "3        3              3",
    "3        4              4",
    "2                     )",
    "3        5            5",
    "2                   )",
    "1                   (",
    "4        4            QUOTIENT",
    "1                     (",
    "4        3              TIMES",
    "3        6              6",
    "1                       (",
    "4        1                PLUS",
    "3        3                3",
    "3        4                4",
    "2                       )",
    "3       10              10",
    "2                     )",
    "1                     (",
    "4        2              DIFFERENCE",
    "3       12              12",
    "3        2              2",
    "2                     )",
    "2                   )",
    "9                   STOP"
  ] },
  { id: "ackermann", name: "Ackermann’s function (with a push-down list)", cards: [
    "C     ACKERMANN'S FUNCTION, WITH A PUSH-DOWN LIST FOR ITS RECURSION",
    "C     WILHELM ACKERMANN (1928) GAVE A FUNCTION THAT CAN BE COMPUTED BUT",
    "C     IS NOT PRIMITIVE RECURSIVE: NO PROGRAM MADE ONLY OF DO LOOPS, HOW-",
    "C     EVER DEEPLY NESTED, CAN COMPUTE IT. THIS IS THE TWO-ARGUMENT FORM",
    "C     OF ROZSA PETER AND RAPHAEL",
    "C     ROBINSON. A(0,N) IS N+1; A(M,0) IS A(M-1,1); AND A(M,N) IS",
    "C     A(M-1, A(M,N-1)). THE DECK NEVER CALLS ITSELF. THE INNER CALL IS",
    "C     WORKED OUT FIRST, AND THE OUTER ONE, WHICH MUST WAIT FOR IT, IS",
    "C     REMEMBERED BY PUSHING ITS M-1 ON A PUSH-DOWN LIST, ISTK. EVERY",
    "C     OTHER CALL IS THE LAST THING ITS CALLER DOES, SO IT NEEDS NO",
    "C     FRAME: IT IS A GO TO WITH NEW VALUES OF M AND N.",
    "C     FIRST THE DECK TRACES ONE CALL, PRINTING EACH STEP WITH THE OUTER",
    "C     CALLS STILL WAITING: HOW MANY, AND THE ONE AT THE TOP OF THE",
    "C     LIST, WHICH WILL TAKE THE NEXT VALUE.",
    "C     THEN IT TABLES A(M,N), THE STEPS EACH TAKES, AND THE DEEPEST THE",
    "C     PUSH-DOWN LIST GOES, FOR N FROM 0 TO 5.",
    "C     DATA CARD (3I5): M AND N OF THE CALL TO TRACE (UP TO 50 STEPS ARE",
    "C     PRINTED), THEN THE LARGEST M FOR THE TABLE (0 TO 3)",
    "C     TRY TRACING A(1,3), OR A(2,2), WHICH TAKES 27 STEPS.",
    "      DIMENSION ISTK(300), NV(6), NC(6), ND(6)",
    "      READ (5,10) MT, NT, MMAX",
    "   10 FORMAT (3I5)",
    "      IF (MMAX .GT. 3) MMAX = 3",
    "      WRITE (6,12) MT, NT",
    "   12 FORMAT (1H1,'ACKERMANN''S FUNCTION'/1H0,'A TRACE OF A(',I1,',',I2,",
    "     1 ')'/1H0,'STEP    CALL',8X,'WAITING   NEXT TO RESUME')",
    "C     THE TRACE",
    "      M = MT",
    "      N = NT",
    "      NS = 0",
    "      NSTEP = 0",
    "   20 NSTEP = NSTEP + 1",
    "      IF (NSTEP .EQ. 51) WRITE (6,21)",
    "   21 FORMAT (1X,'AND SO ON, UNTRACED')",
    "      IF (NSTEP .GT. 50) GO TO 30",
    "      IF (NS .EQ. 0) WRITE (6,25) NSTEP, M, N",
    "      IF (NS .GT. 0) WRITE (6,26) NSTEP, M, N, NS, ISTK(NS)",
    "   25 FORMAT (1X,I4,4X,'A(',I1,',',I4,')',10X,'0')",
    "   26 FORMAT (1X,I4,4X,'A(',I1,',',I4,')',I11,6X,'A(',I1,', ...)')",
    "   30 IF (M .EQ. 0) GO TO 34",
    "      IF (N .EQ. 0) GO TO 32",
    "C     A(M,N) = A(M-1, A(M,N-1)): THE OUTER CALL WAITS ON THE LIST",
    "      NS = NS + 1",
    "      ISTK(NS) = M - 1",
    "      N = N - 1",
    "      GO TO 20",
    "C     A(M,0) = A(M-1,1): A LAST CALL, SO A GO TO",
    "   32 M = M - 1",
    "      N = 1",
    "      GO TO 20",
    "C     A(0,N) = N+1. IF A CALL IS WAITING FOR THIS VALUE, IT IS NEXT",
    "   34 N = N + 1",
    "      IF (NS .EQ. 0) GO TO 36",
    "      M = ISTK(NS)",
    "      NS = NS - 1",
    "      GO TO 20",
    "   36 WRITE (6,37) MT, NT, N, NSTEP",
    "   37 FORMAT (1H0,'A(',I1,',',I2,') =',I4,', IN',I5,' STEPS')",
    "C     THE TABLE: THE SAME CALCULATION, WITHOUT THE TRACE",
    "      WRITE (6,40)",
    "   40 FORMAT (1H0,'N',24X,'0',8X,'1',8X,'2',8X,'3',8X,'4',8X,'5')",
    "      DO 70 MR = 0, MMAX",
    "      DO 60 NR = 0, 5",
    "      M = MR",
    "      N = NR",
    "      NS = 0",
    "      MAXS = 0",
    "      NSTEP = 0",
    "   42 NSTEP = NSTEP + 1",
    "      IF (M .EQ. 0) GO TO 46",
    "      IF (N .EQ. 0) GO TO 44",
    "      NS = NS + 1",
    "      IF (NS .GT. MAXS) MAXS = NS",
    "      ISTK(NS) = M - 1",
    "      N = N - 1",
    "      GO TO 42",
    "   44 M = M - 1",
    "      N = 1",
    "      GO TO 42",
    "   46 N = N + 1",
    "      IF (NS .EQ. 0) GO TO 48",
    "      M = ISTK(NS)",
    "      NS = NS - 1",
    "      GO TO 42",
    "   48 K = NR + 1",
    "      NV(K) = N",
    "      NC(K) = NSTEP",
    "      ND(K) = MAXS",
    "   60 CONTINUE",
    "      WRITE (6,62) MR, NV(1),NV(2),NV(3),NV(4),NV(5),NV(6)",
    "      WRITE (6,63) NC(1),NC(2),NC(3),NC(4),NC(5),NC(6)",
    "      WRITE (6,64) ND(1),ND(2),ND(3),ND(4),ND(5),ND(6)",
    "   62 FORMAT (1H0,'M =',I2,'  A(M,N)',4X,6I9)",
    "   63 FORMAT (1H ,9X,'STEPS',3X,6I9)",
    "   64 FORMAT (1H ,9X,'DEEPEST',1X,6I9)",
    "   70 CONTINUE",
    "      STOP",
    "      END",
    "    2    1    3"
  ] }
]
