[
  { id: "sunny-sixteen", name: "Sunny sixteen (an exposure table)", cards: [
    "C     SUNNY SIXTEEN: AN EXPOSURE TABLE BY RECIPROCITY",
    "C     THE RULE: IN BRIGHT SUN, SET THE LENS TO F/16 AND THE SHUTTER TO",
    "C     ONE OVER THE FILM SPEED. FOR DULLER LIGHT OPEN THE LENS: F/11 FOR",
    "C     A LIGHT OVERCAST, F/8 OVERCAST, F/5.6 HEAVY OVERCAST, F/4 OPEN",
    "C     SHADE; F/22 FOR SAND OR SNOW. THE DECK TURNS THE RULE INTO AN",
    "C     EXPOSURE VALUE, EV = LOG2(N*N/T) FOR STOP N AND TIME T SECONDS,",
    "C     AND PRINTS EVERY STOP AGAINST EVERY SPEED. EACH STEP ACROSS OR",
    "C     DOWN IS ONE STOP, HALF OR DOUBLE THE LIGHT, SO EQUAL VALUES RUN",
    "C     ON A DIAGONAL: THAT IS RECIPROCITY. THEN IT LISTS THE SETTINGS",
    "C     THAT GIVE THE SAME EXPOSURE AS THE RULE.",
    "C     DATA CARD (I5,F5.0): FILM SPEED (ASA, 6 TO 3200), THE STOP THE",
    "C     RULE GIVES FOR THE LIGHT (22, 16, 11, 8, 5.6 OR 4)",
    "C     TRY ASA 400 IN OPEN SHADE (4), OR ASA 25 ON SNOW (22).",
    "      DIMENSION FN(10), IT(11), IEV(11)",
    "      READ (5,10) IASA, STOP",
    "   10 FORMAT (I5,F5.0)",
    "C     THE NOMINAL STOPS AND SPEEDS. STOP K IS K STOPS FROM F/1, AND",
    "C     SPEED J IS J STOPS FROM 1 SECOND, SO EV IS SIMPLY K + J",
    "      FN(1) = 1.4",
    "      FN(2) = 2.0",
    "      FN(3) = 2.8",
    "      FN(4) = 4.0",
    "      FN(5) = 5.6",
    "      FN(6) = 8.0",
    "      FN(7) = 11.0",
    "      FN(8) = 16.0",
    "      FN(9) = 22.0",
    "      FN(10) = 32.0",
    "      IT(1) = 1",
    "      IT(2) = 2",
    "      IT(3) = 4",
    "      IT(4) = 8",
    "      IT(5) = 15",
    "      IT(6) = 30",
    "      IT(7) = 60",
    "      IT(8) = 125",
    "      IT(9) = 250",
    "      IT(10) = 500",
    "      IT(11) = 1000",
    "C     THE RULE: STOP N AT 1/ASA SECOND",
    "      E = ALOG(STOP*STOP*FLOAT(IASA))/ALOG(2.0)",
    "      KEV = INT(E + 0.5)",
    "      IF (STOP .LT. 10.0) WRITE (6,15) IASA, STOP, IASA, E, KEV",
    "      IF (STOP .GE. 10.0) WRITE (6,16) IASA, INT(STOP), IASA, E, KEV",
    "   15 FORMAT (1H1,'SUNNY SIXTEEN'/1H0,'FILM SPEED ASA',I5/1H ,",
    "     1 'THE RULE GIVES F/',F3.1,' AT 1/',I4,' SECOND, EV',F6.2,",
    "     2 ', CALL IT EV',I3)",
    "   16 FORMAT (1H1,'SUNNY SIXTEEN'/1H0,'FILM SPEED ASA',I5/1H ,",
    "     1 'THE RULE GIVES F/',I2,' AT 1/',I4,' SECOND, EV',F6.2,",
    "     2 ', CALL IT EV',I3)",
    "      IF (STOP .GT. 19.0) WRITE (6,21)",
    "      IF (STOP .GT. 13.0 .AND. STOP .LE. 19.0) WRITE (6,22)",
    "      IF (STOP .GT. 9.5 .AND. STOP .LE. 13.0) WRITE (6,23)",
    "      IF (STOP .GT. 6.8 .AND. STOP .LE. 9.5) WRITE (6,24)",
    "      IF (STOP .GT. 4.8 .AND. STOP .LE. 6.8) WRITE (6,25)",
    "      IF (STOP .LE. 4.8) WRITE (6,26)",
    "   21 FORMAT (1H ,'THE LIGHT: SAND OR SNOW IN BRIGHT SUN')",
    "   22 FORMAT (1H ,'THE LIGHT: BRIGHT SUN, SHADOWS SHARP')",
    "   23 FORMAT (1H ,'THE LIGHT: LIGHT OVERCAST, SHADOWS SOFT')",
    "   24 FORMAT (1H ,'THE LIGHT: OVERCAST, SHADOWS BARELY THERE')",
    "   25 FORMAT (1H ,'THE LIGHT: HEAVY OVERCAST, NO SHADOWS')",
    "   26 FORMAT (1H ,'THE LIGHT: OPEN SHADE, OR SUNSET')",
    "      WRITE (6,30)",
    "   30 FORMAT (1H0,'EXPOSURE VALUE OF EVERY SETTING'/1H0,12X,",
    "     1 'SHUTTER, 1/N SECOND'/1H ,'  STOP    ',",
    "     2 '     1     2     4     8    15    30    60   125   250   500',",
    "     3 '  1000'/1H )",
    "      DO 40 K = 1, 10",
    "      DO 35 J = 1, 11",
    "      IEV(J) = K + J - 1",
    "   35 CONTINUE",
    "      IF (K .LT. 7) WRITE (6,36) FN(K), IEV(1),IEV(2),IEV(3),IEV(4),",
    "     1 IEV(5),IEV(6),IEV(7),IEV(8),IEV(9),IEV(10),IEV(11)",
    "      IF (K .GE. 7) WRITE (6,37) INT(FN(K)), IEV(1),IEV(2),IEV(3),",
    "     1 IEV(4),IEV(5),IEV(6),IEV(7),IEV(8),IEV(9),IEV(10),IEV(11)",
    "   36 FORMAT (1X,'  F/',F3.1,3X,11I6)",
    "   37 FORMAT (1X,'  F/',I2,4X,11I6)",
    "   40 CONTINUE",
    "      WRITE (6,45) KEV",
    "   45 FORMAT (1H0,'THE SAME EXPOSURE AS THE RULE, EV',I3,':'/1H )",
    "      N = 0",
    "      DO 60 K = 1, 10",
    "      J = KEV - K + 1",
    "      IF (J .LT. 1 .OR. J .GT. 11) GO TO 60",
    "      N = N + 1",
    "      IF (K .GE. 7) GO TO 55",
    "      IF (J .EQ. 1) WRITE (6,51) FN(K)",
    "      IF (J .GT. 1) WRITE (6,52) FN(K), IT(J)",
    "      GO TO 60",
    "   55 IF (J .EQ. 1) WRITE (6,53) INT(FN(K))",
    "      IF (J .GT. 1) WRITE (6,54) INT(FN(K)), IT(J)",
    "   60 CONTINUE",
    "   51 FORMAT (1X,'  F/',F3.1,'  AT  1 SECOND')",
    "   52 FORMAT (1X,'  F/',F3.1,'  AT  1/',I4,' SECOND')",
    "   53 FORMAT (1X,'  F/',I2,1X,'  AT  1 SECOND')",
    "   54 FORMAT (1X,'  F/',I2,1X,'  AT  1/',I4,' SECOND')",
    "      IF (N .EQ. 0) WRITE (6,62)",
    "   62 FORMAT (1X,'  NONE: THE LIGHT IS OFF THE TABLE')",
    "      WRITE (6,65) N",
    "   65 FORMAT (1H0,I3,' SETTINGS, ONE EXPOSURE. A WIDER STOP GIVES LESS',",
    "     1 ' DEPTH OF FIELD;'/1H ,'    A SHORTER TIME STOPS MORE MOTION.')",
    "      STOP",
    "      END",
    "  100  16."
  ] },
  { id: "characteristic-curve", name: "The characteristic curve (after Hurter and Driffield)", cards: [
    "C     THE CHARACTERISTIC CURVE, AFTER HURTER AND DRIFFIELD (1890)",
    "C     DENSITY OF THE DEVELOPED NEGATIVE PLOTTED AGAINST THE LOGARITHM",
    "C     OF THE EXPOSURE: A TOE WHERE THE FILM BEGINS TO RESPOND, A",
    "C     STRAIGHT LINE WHOSE SLOPE IS CALLED GAMMA, AND A SHOULDER WHERE",
    "C     IT TIRES. DENSITY IS THE LOG OF OPACITY: 0.3 LETS THROUGH HALF",
    "C     THE LIGHT, 1.0 A TENTH. ONE STOP MORE EXPOSURE IS 0.3 FURTHER",
    "C     ALONG, SO THE ZONES 0 TO X STAND 6 CHARACTERS APART ON THE AXIS;",
    "C     PAST ZONE X THE AXIS RUNS ON INTO OVEREXPOSURE AND THE SHOULDER.",
    "C     THE FILM IS A MODEL: LONGER DEVELOPMENT MULTIPLIES EVERY DENSITY",
    "C     ABOVE FOG, AND GAMMA GROWS TOWARD A LIMIT, GINF*(1-EXP(-T/TAU)).",
    "C     ONE CURVE IS DRAWN FOR EACH OF THREE DEVELOPMENT TIMES, AND THE",
    "C     DECK FINDS THE ZONE OF EXPOSURE THAT REACHES THE DENSITY THE",
    "C     SECOND (NORMAL) DEVELOPMENT GIVES ZONE VIII.",
    "C     DATA CARD (5F6.2): GAMMA AT ENDLESS DEVELOPMENT, TIME CONSTANT",
    "C     IN MINUTES, THEN THREE DEVELOPMENT TIMES IN MINUTES",
    "C     TRY TIMES OF 4, 8 AND 16 MINUTES, OR A GINF OF 1.5.",
    "      DIMENSION TD(3), P(72), DZ(11)",
    "      READ (5,10) GINF, TAU, TD(1), TD(2), TD(3)",
    "   10 FORMAT (5F6.2)",
    "C     THE SHAPE: TOE NEAR LOG E = A, SHOULDER NEAR B, SOFTNESS SL",
    "      FOG = 0.10",
    "      A = 0.35",
    "      B = 3.30",
    "      SL = 0.15",
    "      GN = GINF*(1.0 - EXP(-TD(2)/TAU))",
    "      X8 = 0.15 + 0.3*8.0",
    "      DREF = FOG + GN*SL*(ALOG(1.0+EXP((X8-A)/SL))",
    "     1 - ALOG(1.0+EXP((X8-B)/SL)))",
    "      WRITE (6,12)",
    "   12 FORMAT (1H1,'THE CHARACTERISTIC CURVE')",
    "      DO 90 ID = 1, 3",
    "      G = GINF*(1.0 - EXP(-TD(ID)/TAU))",
    "      WRITE (6,15) TD(ID), G",
    "   15 FORMAT (1H0,'DEVELOPED',F6.1,' MINUTES, GAMMA',F5.2/1H ,",
    "     1 'DENSITY')",
    "      DO 40 IR = 1, 16",
    "      DLO = 0.15*FLOAT(16 - IR)",
    "      DHI = DLO + 0.15",
    "      DO 30 IC = 1, 72",
    "      XL = 0.05*FLOAT(IC - 1)",
    "      XR = XL + 0.05",
    "      DL = FOG + G*SL*(ALOG(1.0+EXP((XL-A)/SL))",
    "     1 - ALOG(1.0+EXP((XL-B)/SL)))",
    "      DR = FOG + G*SL*(ALOG(1.0+EXP((XR-A)/SL))",
    "     1 - ALOG(1.0+EXP((XR-B)/SL)))",
    "      P(IC) = 0.0",
    "      IF (DL .LT. DHI .AND. DR .GE. DLO) P(IC) = 1.0",
    "   30 CONTINUE",
    "      WRITE (6,35) DLO, P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),",
    "     1 P(10),P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),",
    "     2 P(20),P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),",
    "     3 P(30),P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),",
    "     4 P(40),P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),",
    "     5 P(50),P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),",
    "     6 P(60),P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68),P(69),",
    "     7 P(70),P(71),P(72)",
    "   35 FORMAT (1X,F5.2,2X,72F1.0)",
    "   40 CONTINUE",
    "      WRITE (6,45)",
    "   45 FORMAT (1H ,'ZONE',5X,'0     I     II    III   IV    V     VI',",
    "     1 '    VII   VIII  IX    X   (OVER)'/1H ,8X,'LOG EXPOSURE, 0.3 ',",
    "     2 '(ONE STOP) TO A ZONE')",
    "C     THE DENSITY OF EACH ZONE ON THIS NEGATIVE",
    "      DO 50 IZ = 1, 11",
    "      X = 0.15 + 0.3*FLOAT(IZ - 1)",
    "      DZ(IZ) = FOG + G*SL*(ALOG(1.0+EXP((X-A)/SL))",
    "     1 - ALOG(1.0+EXP((X-B)/SL)))",
    "   50 CONTINUE",
    "      WRITE (6,55) DZ(1),DZ(2),DZ(3),DZ(4),DZ(5),DZ(6),DZ(7),DZ(8),",
    "     1 DZ(9),DZ(10),DZ(11)",
    "   55 FORMAT (1H ,'D',4X,11F6.2)",
    "C     WHICH ZONE OF EXPOSURE REACHES THE NORMAL ZONE VIII: STEP ALONG",
    "      ZF = 0.0",
    "      DO 60 K = 1, 360",
    "      X = 0.01*FLOAT(K)",
    "      D = FOG + G*SL*(ALOG(1.0+EXP((X-A)/SL))",
    "     1 - ALOG(1.0+EXP((X-B)/SL)))",
    "      IF (D .LT. DREF) GO TO 60",
    "      ZF = (X - 0.15)/0.3",
    "      GO TO 65",
    "   60 CONTINUE",
    "   65 R = DZ(9) - DZ(2)",
    "      IF (ZF .GT. 0.0) WRITE (6,70) R, DREF, ZF",
    "      IF (ZF .LE. 0.0) WRITE (6,71) R, DREF",
    "   70 FORMAT (1H ,'ZONE I TO ZONE VIII SPANS A DENSITY OF',F5.2/1H ,",
    "     1 'THE DENSITY NORMAL DEVELOPMENT GIVES ZONE VIII,',F5.2,",
    "     2 ', IS REACHED AT ZONE',F5.1)",
    "   71 FORMAT (1H ,'ZONE I TO ZONE VIII SPANS A DENSITY OF',F5.2/1H ,",
    "     1 'THE DENSITY NORMAL DEVELOPMENT GIVES ZONE VIII,',F5.2,",
    "     2 ', IS NEVER REACHED')",
    "   90 CONTINUE",
    "      STOP",
    "      END",
    "  1.00  8.00  6.50  8.00 10.50"
  ] },
  { id: "zone-system", name: "The Zone System (after Adams and Archer)", cards: [
    "C     THE ZONE SYSTEM, AFTER ANSEL ADAMS AND FRED ARCHER (ABOUT 1940)",
    "C     ELEVEN ZONES FROM 0, FULL BLACK, TO X, THE WHITE OF THE PAPER.",
    "C     EACH ZONE IS ONE STOP, DOUBLE THE EXPOSURE OF THE ZONE BELOW IT,",
    "C     AND A STEP OF ONE TENTH MORE PAPER IN THE PRINT. THE WEDGE IS",
    "C     PRINTED THROUGH A 4 BY 4 SCREEN, AN ASTERISK FOR INK AND A FULL",
    "C     STOP FOR PAPER. A METER READS ANY SURFACE AS ZONE V, MIDDLE GREY.",
    "C     THE PHOTOGRAPHER PLACES ONE SURFACE ON THE ZONE HE WANTS, AND THE",
    "C     OTHERS FALL WHERE THEIR READINGS PUT THEM, ONE ZONE FOR EACH STOP.",
    "C     THE DECK PRINTS WHERE EACH SURFACE OF A LANDSCAPE FALLS, THE",
    "C     EXPOSURE, AND THE DEVELOPMENT THAT BRINGS THE BRIGHTEST SURFACE TO",
    "C     ZONE VIII: N+1 FOR ONE ZONE MORE, N-1 FOR ONE ZONE LESS.",
    "C     DATA CARDS: (2I5) WHICH SURFACE TO PLACE (1 TO 6), AND ON WHICH",
    "C     ZONE (0 TO 10); (6I5) THE METER READING OF EACH SURFACE, AS AN",
    "C     EXPOSURE VALUE AT THE FILM SPEED IN USE: 1 SHADOW UNDER THE",
    "C     PINES, 2 DARK ROCK, 3 FOLIAGE, 4 WEATHERED WOOD, 5 GRANITE IN",
    "C     SUN, 6 WHITE CLOUD",
    "C     TRY PLACING THE SHADOW ON ZONE II, OR A CLOUD READING OF 16.",
    "      DIMENSION IB(4,4), P(66), IEV(6), IZ(6), Q(11), FN(10), IT(11)",
    "      READ (5,10) IPL, ION",
    "      READ (5,11) IEV(1),IEV(2),IEV(3),IEV(4),IEV(5),IEV(6)",
    "   10 FORMAT (2I5)",
    "   11 FORMAT (6I5)",
    "C     THE SCREEN: AN ORDERED DITHER OF THRESHOLDS 0 TO 15",
    "      IB(1,1) = 0",
    "      IB(1,2) = 8",
    "      IB(1,3) = 2",
    "      IB(1,4) = 10",
    "      IB(2,1) = 12",
    "      IB(2,2) = 4",
    "      IB(2,3) = 14",
    "      IB(2,4) = 6",
    "      IB(3,1) = 3",
    "      IB(3,2) = 11",
    "      IB(3,3) = 1",
    "      IB(3,4) = 9",
    "      IB(4,1) = 15",
    "      IB(4,2) = 7",
    "      IB(4,3) = 13",
    "      IB(4,4) = 5",
    "      WRITE (6,15)",
    "   15 FORMAT (1H1,'THE ZONE SYSTEM'/1H )",
    "C     THE WEDGE: ZONE Z IS 6 CHARACTERS WIDE, INK IN (10-Z) TENTHS",
    "      DO 30 IR = 1, 6",
    "      DO 25 IC = 1, 66",
    "      IZN = (IC - 1)/6",
    "      L = (16*(10 - IZN) + 5)/10",
    "      P(IC) = 0.0",
    "      IF (L .GT. IB(MOD(IR,4)+1, MOD(IC,4)+1)) P(IC) = 1.0",
    "   25 CONTINUE",
    "      WRITE (6,26) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66)",
    "   26 FORMAT (1X,66F1.0)",
    "   30 CONTINUE",
    "      WRITE (6,32)",
    "   32 FORMAT (1H ,'  0     I     II    III   IV    V     VI    VII   ',",
    "     1 'VIII  IX    X'/1H ,'  1     2     4     8     16    32    64',",
    "     2 '    128   256   512   1024  EXPOSURE'/1H ,'  BLACK',25X,",
    "     3 'MIDDLE GREY',7X,'TEXTURE',5X,'PAPER')",
    "C     PLACE ONE SURFACE: GIVE (ZONE - 5) STOPS LESS THAN THE METER SAYS",
    "      KEV = IEV(IPL) + 5 - ION",
    "      WRITE (6,35) IPL, IEV(IPL), ION, KEV",
    "   35 FORMAT (1H0,'SURFACE',I2,' READS EV',I3,'. PLACED ON ZONE',I3,",
    "     1 ', THE EXPOSURE IS EV',I3)",
    "C     A SETTING NEAR 1/60 SECOND",
    "      FN(1) = 1.4",
    "      FN(2) = 2.0",
    "      FN(3) = 2.8",
    "      FN(4) = 4.0",
    "      FN(5) = 5.6",
    "      FN(6) = 8.0",
    "      FN(7) = 11.0",
    "      FN(8) = 16.0",
    "      FN(9) = 22.0",
    "      FN(10) = 32.0",
    "      IT(1) = 1",
    "      IT(2) = 2",
    "      IT(3) = 4",
    "      IT(4) = 8",
    "      IT(5) = 15",
    "      IT(6) = 30",
    "      IT(7) = 60",
    "      IT(8) = 125",
    "      IT(9) = 250",
    "      IT(10) = 500",
    "      IT(11) = 1000",
    "      K = MIN0(MAX0(KEV - 6, 1), 10)",
    "      J = KEV - K + 1",
    "      IF (K .GE. 7) GO TO 37",
    "      IF (J .GE. 2 .AND. J .LE. 11) WRITE (6,36) FN(K), IT(J)",
    "      GO TO 39",
    "   37 IF (J .GE. 2 .AND. J .LE. 11) WRITE (6,34) INT(FN(K)), IT(J)",
    "   34 FORMAT (1H ,'FOR EXAMPLE F/',I2,' AT 1/',I4,' SECOND')",
    "   39 CONTINUE",
    "   36 FORMAT (1H ,'FOR EXAMPLE F/',F3.1,' AT 1/',I4,' SECOND')",
    "      WRITE (6,38)",
    "   38 FORMAT (1H0,'WHERE EACH SURFACE FALLS'/1H )",
    "      IHI = 0",
    "      DO 60 IS = 1, 6",
    "      IZ(IS) = 5 + IEV(IS) - KEV",
    "      IZC = MIN0(MAX0(IZ(IS), 0), 10)",
    "      DO 40 K = 1, 11",
    "      Q(K) = 0.0",
    "      IF (K - 1 .EQ. IZC) Q(K) = 1.0",
    "   40 CONTINUE",
    "      IF (IZ(IS) .GT. IHI) IHI = IZ(IS)",
    "      GO TO (41,42,43,44,45,46), IS",
    "   41 WRITE (6,51) Q(1),Q(2),Q(3),Q(4),Q(5),Q(6),Q(7),Q(8),Q(9),Q(10),",
    "     1 Q(11), IZ(IS)",
    "      GO TO 60",
    "   42 WRITE (6,52) Q(1),Q(2),Q(3),Q(4),Q(5),Q(6),Q(7),Q(8),Q(9),Q(10),",
    "     1 Q(11), IZ(IS)",
    "      GO TO 60",
    "   43 WRITE (6,53) Q(1),Q(2),Q(3),Q(4),Q(5),Q(6),Q(7),Q(8),Q(9),Q(10),",
    "     1 Q(11), IZ(IS)",
    "      GO TO 60",
    "   44 WRITE (6,54) Q(1),Q(2),Q(3),Q(4),Q(5),Q(6),Q(7),Q(8),Q(9),Q(10),",
    "     1 Q(11), IZ(IS)",
    "      GO TO 60",
    "   45 WRITE (6,55) Q(1),Q(2),Q(3),Q(4),Q(5),Q(6),Q(7),Q(8),Q(9),Q(10),",
    "     1 Q(11), IZ(IS)",
    "      GO TO 60",
    "   46 WRITE (6,56) Q(1),Q(2),Q(3),Q(4),Q(5),Q(6),Q(7),Q(8),Q(9),Q(10),",
    "     1 Q(11), IZ(IS)",
    "   60 CONTINUE",
    "   51 FORMAT (1X,11(2X,F1.0,3X),I3,'  SHADOW UNDER THE PINES')",
    "   52 FORMAT (1X,11(2X,F1.0,3X),I3,'  DARK ROCK')",
    "   53 FORMAT (1X,11(2X,F1.0,3X),I3,'  FOLIAGE')",
    "   54 FORMAT (1X,11(2X,F1.0,3X),I3,'  WEATHERED WOOD')",
    "   55 FORMAT (1X,11(2X,F1.0,3X),I3,'  GRANITE IN SUN')",
    "   56 FORMAT (1X,11(2X,F1.0,3X),I3,'  WHITE CLOUD')",
    "      WRITE (6,62)",
    "   62 FORMAT (1H ,'  0     I     II    III   IV    V     VI    VII   ',",
    "     1 'VIII  IX    X')",
    "C     DEVELOPMENT: MOVE THE BRIGHTEST SURFACE TO ZONE VIII",
    "      ND = 8 - IHI",
    "      IF (ND .EQ. 0) WRITE (6,70) IHI",
    "      IF (ND .GT. 0) WRITE (6,71) IHI, ND",
    "      IF (ND .LT. 0) WRITE (6,72) IHI, -ND",
    "   70 FORMAT (1H0,'THE BRIGHTEST SURFACE FALLS ON ZONE',I3,",
    "     1 '. DEVELOP NORMALLY: N.')",
    "   71 FORMAT (1H0,'THE BRIGHTEST SURFACE FALLS ON ZONE',I3,",
    "     1 '. EXPAND IT: DEVELOP N+',I1,'.')",
    "   72 FORMAT (1H0,'THE BRIGHTEST SURFACE FALLS ON ZONE',I3,",
    "     1 '. CONTRACT IT: DEVELOP N-',I1,'.')",
    "      IF (IABS(ND) .GT. 2) WRITE (6,75)",
    "   75 FORMAT (1H ,'MORE THAN TWO ZONES: CHOOSE ANOTHER PLACEMENT, OR',",
    "     1 ' DODGE AND BURN IN THE PRINT.')",
    "      STOP",
    "      END",
    "    1    3",
    "    8   10   11   12   13   14"
  ] },
  { id: "rayograph-by-chance", name: "A rayograph by chance (after Man Ray)", cards: [
    "C     A RAYOGRAPH BY CHANCE, AFTER MAN RAY (1922) AND THE PHOTOGRAMS",
    "C     OF LASZLO MOHOLY-NAGY AND LUCIA MOHOLY",
    "C     NO CAMERA: THINGS ARE DROPPED ON A SHEET OF PHOTOGRAPHIC PAPER",
    "C     AND THE LIGHT IS SWITCHED ON. WHERE THE LIGHT FALLS THE PAPER",
    "C     DEVELOPS BLACK; WHERE A THING LIES IT STAYS WHITE. SO THE PICTURE",
    "C     IS A NEGATIVE: WHITE SHAPES ON BLACK. CHANCE CHOOSES EACH THING",
    "C     AND WHERE IT LANDS: A BUTTON, A WASHER, A PENCIL, A LOOP OF THREAD",
    "C     OR A GLASS, WHICH LETS HALF THE LIGHT THROUGH AND PRINTS GREY",
    "C     THROUGH A 4 BY 4 SCREEN. THE SHEET IS 72 CHARACTERS BY 36 LINES.",
    "C     AN ASTERISK IS BLACK (LIGHT), A FULL STOP IS WHITE (SHADOW).",
    "C     DATA CARD (2I5): SEED (1 TO 30268), THINGS TO DROP (1 TO 12)",
    "C     TRY 2 THINGS FOR A SPARE PRINT, 12 FOR A CROWDED ONE, OR THE SEED",
    "C     1922.",
    "      DIMENSION KT(12), OX(12), OY(12), OR(12), OC(12), OS(12),",
    "     1 IB(4,4), P(72)",
    "      READ (5,10) IX, NT",
    "   10 FORMAT (2I5)",
    "      IB(1,1) = 0",
    "      IB(1,2) = 8",
    "      IB(1,3) = 2",
    "      IB(1,4) = 10",
    "      IB(2,1) = 12",
    "      IB(2,2) = 4",
    "      IB(2,3) = 14",
    "      IB(2,4) = 6",
    "      IB(3,1) = 3",
    "      IB(3,2) = 11",
    "      IB(3,3) = 1",
    "      IB(3,4) = 9",
    "      IB(4,1) = 15",
    "      IB(4,2) = 7",
    "      IB(4,3) = 13",
    "      IB(4,4) = 5",
    "      WRITE (6,12)",
    "   12 FORMAT (1H1,'A RAYOGRAPH BY CHANCE'/1H0,'WHAT FELL ON THE PAPER',",
    "     1 ', AND WHERE (COLUMN, LINE)'/1H )",
    "C     DROP THE THINGS. A LINE IS 5/3 AS TALL AS A CHARACTER IS WIDE,",
    "C     SO DISTANCES ARE MEASURED IN CHARACTER WIDTHS BOTH WAYS",
    "      DO 30 K = 1, NT",
    "      IX = MOD(171*IX, 30269)",
    "      KT(K) = MOD(IX, 5) + 1",
    "      IX = MOD(171*IX, 30269)",
    "      OX(K) = 4.0 + 64.0*FLOAT(IX)/30269.0",
    "      IX = MOD(171*IX, 30269)",
    "      OY(K) = 3.0 + 54.0*FLOAT(IX)/30269.0",
    "      IX = MOD(171*IX, 30269)",
    "      U = FLOAT(IX)/30269.0",
    "      IX = MOD(171*IX, 30269)",
    "      A = 3.14159*FLOAT(IX)/30269.0",
    "      OC(K) = COS(A)",
    "      OS(K) = SIN(A)",
    "      IF (KT(K) .EQ. 1) OR(K) = 3.0 + 2.0*U",
    "      IF (KT(K) .EQ. 2) OR(K) = 4.5 + 2.5*U",
    "      IF (KT(K) .EQ. 3) OR(K) = 9.0 + 7.0*U",
    "      IF (KT(K) .EQ. 4) OR(K) = 6.0 + 5.0*U",
    "      IF (KT(K) .EQ. 5) OR(K) = 6.0 + 3.0*U",
    "      ICX = INT(OX(K)) + 1",
    "      ILN = INT(OY(K)*0.6) + 1",
    "      L = KT(K)",
    "      GO TO (21,22,23,24,25), L",
    "   21 WRITE (6,31) K, ICX, ILN",
    "      GO TO 30",
    "   22 WRITE (6,32) K, ICX, ILN",
    "      GO TO 30",
    "   23 WRITE (6,33) K, ICX, ILN",
    "      GO TO 30",
    "   24 WRITE (6,34) K, ICX, ILN",
    "      GO TO 30",
    "   25 WRITE (6,35) K, ICX, ILN",
    "   30 CONTINUE",
    "   31 FORMAT (1X,I4,'  A BUTTON',10X,2I5)",
    "   32 FORMAT (1X,I4,'  A WASHER',10X,2I5)",
    "   33 FORMAT (1X,I4,'  A PENCIL',10X,2I5)",
    "   34 FORMAT (1X,I4,'  A LOOP OF THREAD',2X,2I5)",
    "   35 FORMAT (1X,I4,'  A GLASS',11X,2I5)",
    "      WRITE (6,38)",
    "   38 FORMAT (1H )",
    "C     EXPOSE: EVERY CELL STARTS WITH FULL LIGHT, 16, AND EACH THING",
    "C     OVER IT TAKES THE LIGHT AWAY, OR HALF OF IT FOR THE GLASS",
    "      DO 80 IR = 1, 36",
    "      Y = (FLOAT(IR) - 0.5)*5.0/3.0",
    "      DO 70 IC = 1, 72",
    "      X = FLOAT(IC) - 0.5",
    "      LT = 16",
    "      DO 60 K = 1, NT",
    "      DX = X - OX(K)",
    "      DY = Y - OY(K)",
    "      D = SQRT(DX*DX + DY*DY)",
    "      L = KT(K)",
    "      GO TO (41,42,43,44,45), L",
    "C     A BUTTON: A SOLID DISC",
    "   41 IF (D .LE. OR(K)) LT = 0",
    "      GO TO 60",
    "C     A WASHER: A RING WITH A HOLE",
    "   42 IF (D .LE. OR(K) .AND. D .GE. 0.45*OR(K)) LT = 0",
    "      GO TO 60",
    "C     A PENCIL: A BAR OF HALF LENGTH OR, HALF WIDTH 0.9",
    "   43 T = DX*OC(K) + DY*OS(K)",
    "      T = AMAX1(-OR(K), AMIN1(OR(K), T))",
    "      EX = DX - T*OC(K)",
    "      EY = DY - T*OS(K)",
    "      IF (EX*EX + EY*EY .LE. 0.81) LT = 0",
    "      GO TO 60",
    "C     A LOOP OF THREAD: A THIN CIRCLE",
    "   44 IF (ABS(D - OR(K)) .LE. 0.9) LT = 0",
    "      GO TO 60",
    "C     A GLASS: HALF THE LIGHT PASSES",
    "   45 IF (D .LE. OR(K)) LT = LT/2",
    "   60 CONTINUE",
    "      P(IC) = 0.0",
    "      IF (LT .GT. IB(MOD(IR,4)+1, MOD(IC,4)+1)) P(IC) = 1.0",
    "   70 CONTINUE",
    "      WRITE (6,75) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68),P(69),P(70),",
    "     7 P(71),P(72)",
    "   75 FORMAT (1X,72F1.0)",
    "   80 CONTINUE",
    "      STOP",
    "      END",
    " 1927    7"
  ] },
  { id: "halftone-screen", name: "A halftone screen (a ball in dots)", cards: [
    "C     A HALFTONE SCREEN: HOW A PHOTOGRAPH IS PRINTED ON A PAGE",
    "C     A PRESS PRINTS ONE INK OR NONE, SO A PHOTOGRAPH IS COPIED THROUGH",
    "C     A SCREEN OF CROSSED LINES THAT BREAKS IT INTO DOTS. A LIGHT TONE",
    "C     GIVES SMALL BLACK DOTS, MIDDLE GREY A CHEQUERBOARD, AND A DARK",
    "C     TONE BLACK WITH SMALL WHITE HOLES. HERE EACH CHARACTER IS INKED",
    "C     WHERE THE PICTURE IS DARKER THAN THE SCREEN'S THRESHOLD, WHICH",
    "C     RISES AND FALLS LIKE AN EGG BOX: 0.5 + 0.25(COS 2PI U + COS 2PI V)",
    "C     IN THE SCREEN'S OWN AXES U AND V, TURNED BY THE SCREEN ANGLE. THE",
    "C     PICTURE IS A BALL LIT FROM THE UPPER LEFT, ON A FLOOR, WITH ITS",
    "C     SHADOW, 72 CHARACTERS BY 36 LINES; BELOW IT A SCALE OF TONES FROM",
    "C     10 TO 100 PER CENT. AN ASTERISK IS INK, A FULL STOP PAPER.",
    "C     DATA CARD (2F5.1): THE PITCH OF THE SCREEN IN CHARACTER WIDTHS",
    "C     (2 TO 8), AND ITS ANGLE IN DEGREES (45 IS USUAL FOR ONE INK)",
    "C     TRY A PITCH OF 6 TO SEE THE DOTS, OR AN ANGLE OF 0.",
    "      DIMENSION P(72)",
    "      READ (5,10) PITCH, ANG",
    "   10 FORMAT (2F5.1)",
    "      PI = 3.14159",
    "      A = ANG*PI/180.0",
    "      CA = COS(A)",
    "      SA = SIN(A)",
    "C     THE PRINTER SETS 10 CHARACTERS TO THE INCH",
    "      RUL = 10.0/PITCH",
    "      WRITE (6,12) PITCH, ANG, RUL",
    "   12 FORMAT (1H1,'A HALFTONE SCREEN'/1H0,'PITCH',F5.1,' CHARACTERS,',",
    "     1 ' ANGLE',F5.1,' DEGREES:',F5.1,' LINES TO THE INCH'/1H ,",
    "     2 '(A NEWSPAPER SCREEN HAS ABOUT 85 LINES TO THE INCH, A MAGAZINE',",
    "     3 '''S 133 TO 150)'/1H )",
    "C     THE LIGHT, FROM THE UPPER LEFT AND THE FRONT",
    "      XL = -0.5",
    "      YL = -0.6",
    "      ZL = 0.62",
    "      DO 80 IR = 1, 39",
    "      Y = (FLOAT(IR) - 0.5)*5.0/3.0",
    "      DO 70 IC = 1, 72",
    "      X = FLOAT(IC) - 0.5",
    "C     THE PICTURE: DARKNESS FROM 0 (WHITE) TO 1 (BLACK)",
    "C     A GREY WALL, DARKER LOWER DOWN, AND A PALER FLOOR",
    "      D = 0.25 + 0.15*Y/45.0",
    "      IF (Y .GT. 45.0) D = 0.15 + 0.15*(Y - 45.0)/15.0",
    "C     THE SHADOW ON THE FLOOR",
    "      SX = (X - 44.0)/18.0",
    "      SY = (Y - 51.0)/4.5",
    "      IF (SX*SX + SY*SY .LE. 1.0) D = 0.95",
    "C     THE BALL",
    "      BX = (X - 30.0)/16.0",
    "      BY = (Y - 30.0)/16.0",
    "      R2 = BX*BX + BY*BY",
    "      IF (R2 .GT. 1.0) GO TO 50",
    "      BZ = SQRT(1.0 - R2)",
    "      B = AMAX1(0.0, BX*XL + BY*YL + BZ*ZL)",
    "      D = 0.97 - 0.97*B",
    "C     BELOW THE PICTURE, A SCALE OF TEN TONES",
    "   50 IF (IR .GT. 36) D = 0.1*FLOAT((IC - 1)/7 + 1)",
    "      IF (IR .GT. 36 .AND. IC .GT. 70) D = 0.0",
    "C     THE SCREEN, TRIED AT FOUR POINTS IN THE CHARACTER: INK IF THE",
    "C     PICTURE IS DARKER THAN THE THRESHOLD AT TWO OR MORE OF THEM",
    "      N = 0",
    "      DO 60 K = 1, 4",
    "      XS = X - 0.25 + 0.5*FLOAT(MOD(K-1,2))",
    "      YS = Y - 5.0/12.0 + 5.0/6.0*FLOAT((K-1)/2)",
    "      U = (XS*CA + YS*SA)/PITCH",
    "      V = (YS*CA - XS*SA)/PITCH",
    "      T = 0.5 + 0.25*(COS(2.0*PI*U) + COS(2.0*PI*V))",
    "      IF (D .GT. T) N = N + 1",
    "   60 CONTINUE",
    "      P(IC) = 0.0",
    "      IF (N .GE. 2) P(IC) = 1.0",
    "   70 CONTINUE",
    "      IF (IR .EQ. 37) WRITE (6,72)",
    "   72 FORMAT (1H )",
    "      WRITE (6,75) P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8),P(9),P(10),",
    "     1 P(11),P(12),P(13),P(14),P(15),P(16),P(17),P(18),P(19),P(20),",
    "     2 P(21),P(22),P(23),P(24),P(25),P(26),P(27),P(28),P(29),P(30),",
    "     3 P(31),P(32),P(33),P(34),P(35),P(36),P(37),P(38),P(39),P(40),",
    "     4 P(41),P(42),P(43),P(44),P(45),P(46),P(47),P(48),P(49),P(50),",
    "     5 P(51),P(52),P(53),P(54),P(55),P(56),P(57),P(58),P(59),P(60),",
    "     6 P(61),P(62),P(63),P(64),P(65),P(66),P(67),P(68),P(69),P(70),",
    "     7 P(71),P(72)",
    "   75 FORMAT (1X,72F1.0)",
    "   80 CONTINUE",
    "      WRITE (6,85)",
    "   85 FORMAT (1H ,'  10%    20%    30%    40%    50%    60%    70%    ',",
    "     1 '80%    90%   100%')",
    "      STOP",
    "      END",
    "  5.0 45.0"
  ] }
]
